server:
  port: 8080
logging:
  level:
    root: INFO
  file: logs/${spring.application.name}.log

upload:
    work-folder-name: /root/process #文件存储路径

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_MEMBERS}
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
spring:
  application:
    name: flow-provider

  datasource:
    url: jdbc:mysql://${JDBC_URL}:${JDBC_PORT}/peak_flow?characterEncoding=utf8&useSSL=true
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 20000


hystrix:
  propagate:
    request-attribute:
      enabled: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000

cos:
  url: https://masspick-1255853614.cos-website.ap-shanghai.myqcloud.com
  dir: masspick/produc/peak-flow/
  accessKey: AKIDPfAYmp5OuNgolWvVq35wd9TdcQ2THurd
  secretKey: kM1Vo6KSVSJ3iGk9RcfXFoDYiiXB7uVu
  region: ap-shanghai
  bucket:
    name: masspick-1255853614
