server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

spring:
  datasource:
    url: jdbc:mysql://192.168.111.210:3306/resource?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
  redis:
    database: 0
    host: localhost
    #password: # Login password of the redis server.
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接数
        max-wait: -1 #最大等待时间
        min-idle: 0 #初始化连接数
