spring:
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  profiles:
      active: ${ENV}


security:
  jwt:
    secret: k09BQnaF
    max-expiration: 604800 #7Days
    min-expiration: 1800

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml