package com.masspick.peak.etp.mapper.legal;

import com.masspick.peak.model.legal.CrdCourtDp;
import org.apache.ibatis.annotations.Mapper;

/**
 * CrdCourtDpMapper
 */
@Mapper
public interface CrdCourtDpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court_dp
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     * @return int
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court_dp
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     * @return int
     */
    int insert(CrdCourtDp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court_dp
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     * @return int
     */
    int insertSelective(CrdCourtDp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court_dp
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     * @return int
     */
    CrdCourtDp selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court_dp
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     * @return int
     */
    int updateByPrimaryKeySelective(CrdCourtDp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.crd_court_dp
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     * @return int
     */
    int updateByPrimaryKey(CrdCourtDp record);
}
