package com.masspick.peak.etp.mapper.legal;

import com.masspick.peak.model.legal.Executed;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * ExecutedMapper
 */
@Mapper
public interface ExecutedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.executed_all
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     * @return int
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.executed_all
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     * @return int
     */
    int insert(Executed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.executed_all
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     * @return int
     */
    int insertSelective(Executed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.executed_all
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     * @return int
     */
    Executed selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.executed_all
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     * @return int
     */
    int updateByPrimaryKeySelective(Executed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.executed_all
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     * @return int
     */
    int updateByPrimaryKey(Executed record);

    /**
     * @param executed
     * @return List<Executed>
     */
    List<Executed> findByEtpId(@Param("executed") String executed);
}
