package com.masspick.peak.model.tax;

/**
 * TaxBalanceNormal
 */
public class TaxBalanceNormal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_balance_normal.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_balance_normal.year_begin_equity
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double yearBeginEquity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_balance_normal.term_end_equity
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double termEndEquity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_balance_normal.debt_equity_item
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String debtEquityItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_balance_normal.year_begin_asset
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double yearBeginAsset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_balance_normal.year_end_asset
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double yearEndAsset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_balance_normal.update_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_balance_normal.asset_item
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String assetItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_balance_normal.seq_no
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_balance_normal.out_id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String outId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_balance_normal.id
     *
     * @return the value of tax_balance_normal.id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_balance_normal.id
     *
     * @param id the value for tax_balance_normal.id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_balance_normal.year_begin_equity
     *
     * @return the value of tax_balance_normal.year_begin_equity
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getYearBeginEquity() {
        return yearBeginEquity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_balance_normal.year_begin_equity
     *
     * @param yearBeginEquity the value for tax_balance_normal.year_begin_equity
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setYearBeginEquity(Double yearBeginEquity) {
        this.yearBeginEquity = yearBeginEquity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_balance_normal.term_end_equity
     *
     * @return the value of tax_balance_normal.term_end_equity
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getTermEndEquity() {
        return termEndEquity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_balance_normal.term_end_equity
     *
     * @param termEndEquity the value for tax_balance_normal.term_end_equity
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setTermEndEquity(Double termEndEquity) {
        this.termEndEquity = termEndEquity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_balance_normal.debt_equity_item
     *
     * @return the value of tax_balance_normal.debt_equity_item
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getDebtEquityItem() {
        return debtEquityItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_balance_normal.debt_equity_item
     *
     * @param debtEquityItem the value for tax_balance_normal.debt_equity_item
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setDebtEquityItem(String debtEquityItem) {
        this.debtEquityItem = debtEquityItem == null ? null : debtEquityItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_balance_normal.year_begin_asset
     *
     * @return the value of tax_balance_normal.year_begin_asset
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getYearBeginAsset() {
        return yearBeginAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_balance_normal.year_begin_asset
     *
     * @param yearBeginAsset the value for tax_balance_normal.year_begin_asset
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setYearBeginAsset(Double yearBeginAsset) {
        this.yearBeginAsset = yearBeginAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_balance_normal.year_end_asset
     *
     * @return the value of tax_balance_normal.year_end_asset
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getYearEndAsset() {
        return yearEndAsset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_balance_normal.year_end_asset
     *
     * @param yearEndAsset the value for tax_balance_normal.year_end_asset
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setYearEndAsset(Double yearEndAsset) {
        this.yearEndAsset = yearEndAsset;
    }

    /**
     * @return String
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * @param updateDate
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_balance_normal.asset_item
     *
     * @return the value of tax_balance_normal.asset_item
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getAssetItem() {
        return assetItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_balance_normal.asset_item
     *
     * @param assetItem the value for tax_balance_normal.asset_item
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setAssetItem(String assetItem) {
        this.assetItem = assetItem == null ? null : assetItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_balance_normal.seq_no
     *
     * @return the value of tax_balance_normal.seq_no
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_balance_normal.seq_no
     *
     * @param seqNo the value for tax_balance_normal.seq_no
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo == null ? null : seqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_balance_normal.out_id
     *
     * @return the value of tax_balance_normal.out_id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_balance_normal.out_id
     *
     * @param outId the value for tax_balance_normal.out_id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }
}
