package com.masspick.peak.model.tax;

/**
 * TaxEquityChangeNormal
 */
public class TaxEquityChangeNormal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.last_year_surplus
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double lastYearSurplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.last_year_undis_profit
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double lastYearUndisProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.last_year_total_equity
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double lastYearTotalEquity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.year_reserve
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double yearReserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.year_stock
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double yearStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.year_surplus
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double yearSurplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.year_undis_profit
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double yearUndisProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.year_total_equity
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double yearTotalEquity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.last_year_real_cap
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double lastYearRealCap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.last_year_cap_reserve
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double lastYearCapReserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.last_year_stock
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double lastYearStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.update_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.out_id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String outId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.seq_no
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.category
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_equity_change_normal.year_real_cap
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double yearRealCap;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.id
     *
     * @return the value of tax_equity_change_normal.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.id
     *
     * @param id the value for tax_equity_change_normal.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.last_year_surplus
     *
     * @return the value of tax_equity_change_normal.last_year_surplus
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getLastYearSurplus() {
        return lastYearSurplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.last_year_surplus
     *
     * @param lastYearSurplus the value for tax_equity_change_normal.last_year_surplus
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setLastYearSurplus(Double lastYearSurplus) {
        this.lastYearSurplus = lastYearSurplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.last_year_undis_profit
     *
     * @return the value of tax_equity_change_normal.last_year_undis_profit
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getLastYearUndisProfit() {
        return lastYearUndisProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.last_year_undis_profit
     *
     * @param lastYearUndisProfit the value for tax_equity_change_normal.last_year_undis_profit
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setLastYearUndisProfit(Double lastYearUndisProfit) {
        this.lastYearUndisProfit = lastYearUndisProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.last_year_total_equity
     *
     * @return the value of tax_equity_change_normal.last_year_total_equity
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getLastYearTotalEquity() {
        return lastYearTotalEquity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.last_year_total_equity
     *
     * @param lastYearTotalEquity the value for tax_equity_change_normal.last_year_total_equity
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setLastYearTotalEquity(Double lastYearTotalEquity) {
        this.lastYearTotalEquity = lastYearTotalEquity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.year_reserve
     *
     * @return the value of tax_equity_change_normal.year_reserve
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getYearReserve() {
        return yearReserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.year_reserve
     *
     * @param yearReserve the value for tax_equity_change_normal.year_reserve
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setYearReserve(Double yearReserve) {
        this.yearReserve = yearReserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.year_stock
     *
     * @return the value of tax_equity_change_normal.year_stock
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getYearStock() {
        return yearStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.year_stock
     *
     * @param yearStock the value for tax_equity_change_normal.year_stock
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setYearStock(Double yearStock) {
        this.yearStock = yearStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.year_surplus
     *
     * @return the value of tax_equity_change_normal.year_surplus
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getYearSurplus() {
        return yearSurplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.year_surplus
     *
     * @param yearSurplus the value for tax_equity_change_normal.year_surplus
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setYearSurplus(Double yearSurplus) {
        this.yearSurplus = yearSurplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.year_undis_profit
     *
     * @return the value of tax_equity_change_normal.year_undis_profit
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getYearUndisProfit() {
        return yearUndisProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.year_undis_profit
     *
     * @param yearUndisProfit the value for tax_equity_change_normal.year_undis_profit
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setYearUndisProfit(Double yearUndisProfit) {
        this.yearUndisProfit = yearUndisProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.year_total_equity
     *
     * @return the value of tax_equity_change_normal.year_total_equity
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getYearTotalEquity() {
        return yearTotalEquity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.year_total_equity
     *
     * @param yearTotalEquity the value for tax_equity_change_normal.year_total_equity
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setYearTotalEquity(Double yearTotalEquity) {
        this.yearTotalEquity = yearTotalEquity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.last_year_real_cap
     *
     * @return the value of tax_equity_change_normal.last_year_real_cap
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getLastYearRealCap() {
        return lastYearRealCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.last_year_real_cap
     *
     * @param lastYearRealCap the value for tax_equity_change_normal.last_year_real_cap
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setLastYearRealCap(Double lastYearRealCap) {
        this.lastYearRealCap = lastYearRealCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.last_year_cap_reserve
     *
     * @return the value of tax_equity_change_normal.last_year_cap_reserve
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getLastYearCapReserve() {
        return lastYearCapReserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.last_year_cap_reserve
     *
     * @param lastYearCapReserve the value for tax_equity_change_normal.last_year_cap_reserve
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setLastYearCapReserve(Double lastYearCapReserve) {
        this.lastYearCapReserve = lastYearCapReserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.last_year_stock
     *
     * @return the value of tax_equity_change_normal.last_year_stock
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getLastYearStock() {
        return lastYearStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.last_year_stock
     *
     * @param lastYearStock the value for tax_equity_change_normal.last_year_stock
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setLastYearStock(Double lastYearStock) {
        this.lastYearStock = lastYearStock;
    }

    /**
     * @return String
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * @param updateDate
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.out_id
     *
     * @return the value of tax_equity_change_normal.out_id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.out_id
     *
     * @param outId the value for tax_equity_change_normal.out_id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.seq_no
     *
     * @return the value of tax_equity_change_normal.seq_no
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.seq_no
     *
     * @param seqNo the value for tax_equity_change_normal.seq_no
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo == null ? null : seqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.category
     *
     * @return the value of tax_equity_change_normal.category
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.category
     *
     * @param category the value for tax_equity_change_normal.category
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_equity_change_normal.year_real_cap
     *
     * @return the value of tax_equity_change_normal.year_real_cap
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getYearRealCap() {
        return yearRealCap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_equity_change_normal.year_real_cap
     *
     * @param yearRealCap the value for tax_equity_change_normal.year_real_cap
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setYearRealCap(Double yearRealCap) {
        this.yearRealCap = yearRealCap;
    }
}
