package com.masspick.peak.model.tax;

/**
 * TaxGradeInfo
 */
public class TaxGradeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_grade_info.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_grade_info.year
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_grade_info.grade
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_grade_info.tax_office
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String taxOffice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_grade_info.id
     *
     * @return the value of tax_grade_info.id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_grade_info.id
     *
     * @param id the value for tax_grade_info.id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_grade_info.year
     *
     * @return the value of tax_grade_info.year
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_grade_info.year
     *
     * @param year the value for tax_grade_info.year
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_grade_info.grade
     *
     * @return the value of tax_grade_info.grade
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_grade_info.grade
     *
     * @param grade the value for tax_grade_info.grade
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_grade_info.tax_office
     *
     * @return the value of tax_grade_info.tax_office
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getTaxOffice() {
        return taxOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_grade_info.tax_office
     *
     * @param taxOffice the value for tax_grade_info.tax_office
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setTaxOffice(String taxOffice) {
        this.taxOffice = taxOffice == null ? null : taxOffice.trim();
    }
}
