package com.masspick.peak.model.tax;

/**
 * TaxInspectInfoWithBLOBs
 */
public class TaxInspectInfoWithBLOBs extends TaxInspectInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_inspect_info.inspect_content
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String inspectContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_inspect_info.inspect_conclusion
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String inspectConclusion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_inspect_info.inspect_content
     *
     * @return the value of tax_inspect_info.inspect_content
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getInspectContent() {
        return inspectContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_inspect_info.inspect_content
     *
     * @param inspectContent the value for tax_inspect_info.inspect_content
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setInspectContent(String inspectContent) {
        this.inspectContent = inspectContent == null ? null : inspectContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_inspect_info.inspect_conclusion
     *
     * @return the value of tax_inspect_info.inspect_conclusion
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getInspectConclusion() {
        return inspectConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_inspect_info.inspect_conclusion
     *
     * @param inspectConclusion the value for tax_inspect_info.inspect_conclusion
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setInspectConclusion(String inspectConclusion) {
        this.inspectConclusion = inspectConclusion == null ? null : inspectConclusion.trim();
    }
}
