package com.masspick.peak.model.tax;

/**
 * TaxIllegalInfo
 */
public class TaxIllegalInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.reg_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.fact
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String fact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.category
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.handle_state_code
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String handleStateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.handle_state_name
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String handleStateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.start_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.end_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.illegal_name
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String illegalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.case_mark
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String caseMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.cancel_sign
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String cancelSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_illegal_info.cancel_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String cancelDate;

    /**
     * Gets id
     *
     * @return value of id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets regDate
     *
     * @return value of regDate
     */
    public String getRegDate() {
        return regDate;
    }

    /**
     * @param regDate
     */
    public void setRegDate(String regDate) {
        this.regDate = regDate;
    }

    /**
     * Gets fact
     *
     * @return value of fact
     */
    public String getFact() {
        return fact;
    }

    /**
     * @param fact
     */
    public void setFact(String fact) {
        this.fact = fact;
    }

    /**
     * Gets category
     *
     * @return value of category
     */
    public String getCategory() {
        return category;
    }

    /**
     * @param category
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Gets handleStateCode
     *
     * @return value of handleStateCode
     */
    public String getHandleStateCode() {
        return handleStateCode;
    }

    /**
     * @param handleStateCode
     */
    public void setHandleStateCode(String handleStateCode) {
        this.handleStateCode = handleStateCode;
    }

    /**
     * Gets handleStateName
     *
     * @return value of handleStateName
     */
    public String getHandleStateName() {
        return handleStateName;
    }

    /**
     * @param handleStateName
     */
    public void setHandleStateName(String handleStateName) {
        this.handleStateName = handleStateName;
    }

    /**
     * Gets startDate
     *
     * @return value of startDate
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * @param startDate
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    /**
     * Gets endDate
     *
     * @return value of endDate
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * @param endDate
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * Gets illegalName
     *
     * @return value of illegalName
     */
    public String getIllegalName() {
        return illegalName;
    }

    /**
     * @param illegalName
     */
    public void setIllegalName(String illegalName) {
        this.illegalName = illegalName;
    }

    /**
     * Gets caseMark
     *
     * @return value of caseMark
     */
    public String getCaseMark() {
        return caseMark;
    }

    /**
     * @param caseMark
     */
    public void setCaseMark(String caseMark) {
        this.caseMark = caseMark;
    }

    /**
     * Gets cancelSign
     *
     * @return value of cancelSign
     */
    public String getCancelSign() {
        return cancelSign;
    }

    /**
     * @param cancelSign
     */
    public void setCancelSign(String cancelSign) {
        this.cancelSign = cancelSign;
    }

    /**
     * Gets cancelDate
     *
     * @return value of cancelDate
     */
    public String getCancelDate() {
        return cancelDate;
    }

    /**
     * @param cancelDate
     */
    public void setCancelDate(String cancelDate) {
        this.cancelDate = cancelDate;
    }
}
