package com.masspick.peak.model.tax;

/**
 * TaxLevyInfo
 */
public class TaxLevyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.open_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.payment_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String paymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.tax_start_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String taxStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.tax_end_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String taxEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.collect_item
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String collectItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.tax_type
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String taxType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.tax_state
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String taxState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.base_tax
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double baseTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.tax_rate
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.paid_tax
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double paidTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_levy_info.payable_tax
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double payableTax;

    /**
     * Gets id
     *
     * @return value of id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Gets openDate
     *
     * @return value of openDate
     */
    public String getOpenDate() {
        return openDate;
    }

    /**
     * @param openDate
     */
    public void setOpenDate(String openDate) {
        this.openDate = openDate;
    }

    /**
     * Gets paymentDate
     *
     * @return value of paymentDate
     */
    public String getPaymentDate() {
        return paymentDate;
    }

    /**
     * @param paymentDate
     */
    public void setPaymentDate(String paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * Gets taxStartDate
     *
     * @return value of taxStartDate
     */
    public String getTaxStartDate() {
        return taxStartDate;
    }

    /**
     * @param taxStartDate
     */
    public void setTaxStartDate(String taxStartDate) {
        this.taxStartDate = taxStartDate;
    }

    /**
     * Gets taxEndDate
     *
     * @return value of taxEndDate
     */
    public String getTaxEndDate() {
        return taxEndDate;
    }

    /**
     * @param taxEndDate
     */
    public void setTaxEndDate(String taxEndDate) {
        this.taxEndDate = taxEndDate;
    }

    /**
     * Gets collectItem
     *
     * @return value of collectItem
     */
    public String getCollectItem() {
        return collectItem;
    }

    /**
     * @param collectItem
     */
    public void setCollectItem(String collectItem) {
        this.collectItem = collectItem;
    }

    /**
     * Gets taxType
     *
     * @return value of taxType
     */
    public String getTaxType() {
        return taxType;
    }

    /**
     * @param taxType
     */
    public void setTaxType(String taxType) {
        this.taxType = taxType;
    }

    /**
     * Gets taxState
     *
     * @return value of taxState
     */
    public String getTaxState() {
        return taxState;
    }

    /**
     * @param taxState
     */
    public void setTaxState(String taxState) {
        this.taxState = taxState;
    }

    /**
     * Gets baseTax
     *
     * @return value of baseTax
     */
    public Double getBaseTax() {
        return baseTax;
    }

    /**
     * @param baseTax
     */
    public void setBaseTax(Double baseTax) {
        this.baseTax = baseTax;
    }

    /**
     * Gets taxRate
     *
     * @return value of taxRate
     */
    public Double getTaxRate() {
        return taxRate;
    }

    /**
     * @param taxRate
     */
    public void setTaxRate(Double taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * Gets paidTax
     *
     * @return value of paidTax
     */
    public Double getPaidTax() {
        return paidTax;
    }

    /**
     * @param paidTax
     */
    public void setPaidTax(Double paidTax) {
        this.paidTax = paidTax;
    }

    /**
     * Gets payableTax
     *
     * @return value of payableTax
     */
    public Double getPayableTax() {
        return payableTax;
    }

    /**
     * @param payableTax
     */
    public void setPayableTax(Double payableTax) {
        this.payableTax = payableTax;
    }
}
