package com.masspick.peak.etp.mapper.etp;

import com.masspick.peak.model.etp.EtpAlter;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * EtpAlterMapper
 */
@Mapper
public interface EtpAlterMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_alter_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_alter_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insert(EtpAlter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_alter_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insertSelective(EtpAlter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_alter_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    EtpAlter selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_alter_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKeySelective(EtpAlter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_alter_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKey(EtpAlter record);

    /**
     * @param etpId
     * @return List<EtpAlter>
     */
    List<EtpAlter> findByEtpId(@Param("etpId") String etpId);
}
