package com.masspick.peak.etp.mapper.etp;

import com.masspick.peak.model.etp.EtpBranch;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;


/**
 * EtpBranchMapper
 */
@Mapper
public interface EtpBranchMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_branch_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_branch_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insert(EtpBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_branch_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insertSelective(EtpBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_branch_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    EtpBranch selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_branch_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKeySelective(EtpBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_branch_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKey(EtpBranch record);

    /**
     * @param etpId
     * @return List
     */
    List<EtpBranch> findByEtpId(@Param("etpId") String etpId);
}

