package com.masspick.peak.etp.mapper.etp;

import com.masspick.peak.model.etp.EtpChattel;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * EtpChattelMapper
 */
@Mapper
public interface EtpChattelMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_chattel_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_chattel_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insert(EtpChattel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_chattel_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insertSelective(EtpChattel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_chattel_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    EtpChattel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_chattel_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKeySelective(EtpChattel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_chattel_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKey(EtpChattel record);

    /**
     * @param etpId
     * @return List<EtpChattel>
     */
    List<EtpChattel> findByEtpId(@Param("etpId") String etpId);
}
