package com.masspick.peak.etp.mapper.etp;

import com.masspick.peak.model.etp.EtpPunish;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * EtpPunishMapper
 */
@Mapper
public interface EtpPunishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_punish_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_punish_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    int insert(EtpPunish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_punish_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    int insertSelective(EtpPunish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_punish_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    EtpPunish selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_punish_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    int updateByPrimaryKeySelective(EtpPunish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_punish_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    int updateByPrimaryKey(EtpPunish record);

    /**
     * @param etpId
     * @return List<EtpPunish>
     */
    List<EtpPunish> findByEtpId(@Param("etpId") String etpId);
}
