package com.masspick.peak.etp.mapper.etp;

import com.masspick.peak.model.etp.EtpShareholder;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * EtpShareholderMapper
 */
@Mapper
public interface EtpShareholderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shareholder_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shareholder_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insert(EtpShareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shareholder_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insertSelective(EtpShareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shareholder_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    EtpShareholder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shareholder_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKeySelective(EtpShareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shareholder_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKey(EtpShareholder record);

    /**
     * @param etpId
     * @return List<EtpShareholder>
     */
    List<EtpShareholder> findByEtpId(@Param("etpId") String etpId);

    /**
     * @param shareholder
     * @return List<EtpShareholder>
     */
    List<EtpShareholder> findByShareholder(@Param("shareholder") String shareholder);
}
