package com.masspick.peak.etp.mapper.etp;

import com.masspick.peak.model.etp.EtpSampling;
import org.apache.ibatis.annotations.Mapper;

/**
 * EtpSamplingMapper
 */
@Mapper
public interface EtpSamplingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_sampling_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_sampling_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insert(EtpSampling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_sampling_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insertSelective(EtpSampling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_sampling_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    EtpSampling selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_sampling_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKeySelective(EtpSampling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_sampling_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKey(EtpSampling record);
}
