package com.masspick.peak.etp.mapper.etp;

import com.masspick.peak.model.etp.EtpSharesFrost;
import org.apache.ibatis.annotations.Mapper;

/**
 * EtpSharesFrostMapper
 */
@Mapper
public interface EtpSharesFrostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shares_frost_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shares_frost_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insert(EtpSharesFrost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shares_frost_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insertSelective(EtpSharesFrost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shares_frost_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    EtpSharesFrost selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shares_frost_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKeySelective(EtpSharesFrost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_shares_frost_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKey(EtpSharesFrost record);
}
