package com.masspick.peak.etp.mapper.etp;

import com.masspick.peak.model.etp.EtpStockChange;
import org.apache.ibatis.annotations.Mapper;

/**
 * EtpStockChangeMapper
 */
@Mapper
public interface EtpStockChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_change_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_change_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    int insert(EtpStockChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_change_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    int insertSelective(EtpStockChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_change_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    EtpStockChange selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_change_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    int updateByPrimaryKeySelective(EtpStockChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_change_all
     *
     * @return int
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     */
    int updateByPrimaryKey(EtpStockChange record);
}
