package com.masspick.peak.etp.mapper.etp;

import com.masspick.peak.model.etp.EtpSeniorManager;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * EtpSeniorManagerMapper
 */
@Mapper
public interface EtpSeniorManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_senior_manager_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_senior_manager_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insert(EtpSeniorManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_senior_manager_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insertSelective(EtpSeniorManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_senior_manager_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    EtpSeniorManager selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_senior_manager_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKeySelective(EtpSeniorManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_senior_manager_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKey(EtpSeniorManager record);

    /**
     * @param etpId
     * @return List<EtpSeniorManager>
     */
    List<EtpSeniorManager> findByEtpId(@Param("etpId") String etpId);
}
