package com.masspick.peak.etp.mapper.etp;

import com.masspick.peak.model.etp.EtpStock;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * EtpStockMapper
 */
@Mapper
public interface EtpStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insert(EtpStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int insertSelective(EtpStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    EtpStock selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKeySelective(EtpStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.etp_stock_all
     *
     * @mbggenerated Mon Jun 11 10:53:45 CST 2018
     * @return int
     */
    int updateByPrimaryKey(EtpStock record);

    /**
     * @param etpId
     * @return List<EtpStock>
     */
    List<EtpStock> findByEtpId(@Param("etpId") String etpId);
}
