pipeline {
    agent { 
        node { label 'maven' } 
    }
    stages {
        stage('Deploy') {
            steps {
               dir('peak-parent'){
                  sh 'mvn deploy'
               }
            }
        }
    }
}