package com.masspick.peak.model.legal;

import java.util.Date;

/**
 * Breakfaith
 */
public class Breakfaith {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.id
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.case_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String caseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.execute_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String executeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.company
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.province
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.city
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.area
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.clients
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String clients;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.court_name
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String courtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.data_from
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Integer dataFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.department
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.detail
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.detail_link
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String detailLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.id_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String idNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.gender
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.age
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.judges
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String judges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.liability
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String liability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.org_code
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.performance
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String performance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.person_name
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.rep_name
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String repName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.source
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.summary
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.flag
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.publish_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.open_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.modify_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.collect_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date collectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.create_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.breakfaith_all.update_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.id
     *
     * @return the value of public.breakfaith_all.id
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.id
     *
     * @param id the value for public.breakfaith_all.id
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.case_num
     *
     * @return the value of public.breakfaith_all.case_num
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCaseNum() {
        return caseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.case_num
     *
     * @param caseNum the value for public.breakfaith_all.case_num
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCaseNum(String caseNum) {
        this.caseNum = caseNum == null ? null : caseNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.execute_num
     *
     * @return the value of public.breakfaith_all.execute_num
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getExecuteNum() {
        return executeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.execute_num
     *
     * @param executeNum the value for public.breakfaith_all.execute_num
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setExecuteNum(String executeNum) {
        this.executeNum = executeNum == null ? null : executeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.company
     *
     * @return the value of public.breakfaith_all.company
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.company
     *
     * @param company the value for public.breakfaith_all.company
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.province
     *
     * @return the value of public.breakfaith_all.province
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.province
     *
     * @param province the value for public.breakfaith_all.province
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.city
     *
     * @return the value of public.breakfaith_all.city
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.city
     *
     * @param city the value for public.breakfaith_all.city
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.area
     *
     * @return the value of public.breakfaith_all.area
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.area
     *
     * @param area the value for public.breakfaith_all.area
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.clients
     *
     * @return the value of public.breakfaith_all.clients
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getClients() {
        return clients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.clients
     *
     * @param clients the value for public.breakfaith_all.clients
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setClients(String clients) {
        this.clients = clients == null ? null : clients.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.court_name
     *
     * @return the value of public.breakfaith_all.court_name
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCourtName() {
        return courtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.court_name
     *
     * @param courtName the value for public.breakfaith_all.court_name
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCourtName(String courtName) {
        this.courtName = courtName == null ? null : courtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.data_from
     *
     * @return the value of public.breakfaith_all.data_from
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Integer getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.data_from
     *
     * @param dataFrom the value for public.breakfaith_all.data_from
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setDataFrom(Integer dataFrom) {
        this.dataFrom = dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.department
     *
     * @return the value of public.breakfaith_all.department
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.department
     *
     * @param department the value for public.breakfaith_all.department
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.detail
     *
     * @return the value of public.breakfaith_all.detail
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.detail
     *
     * @param detail the value for public.breakfaith_all.detail
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.detail_link
     *
     * @return the value of public.breakfaith_all.detail_link
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getDetailLink() {
        return detailLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.detail_link
     *
     * @param detailLink the value for public.breakfaith_all.detail_link
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setDetailLink(String detailLink) {
        this.detailLink = detailLink == null ? null : detailLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.id_num
     *
     * @return the value of public.breakfaith_all.id_num
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.id_num
     *
     * @param idNum the value for public.breakfaith_all.id_num
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum == null ? null : idNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.gender
     *
     * @return the value of public.breakfaith_all.gender
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.gender
     *
     * @param gender the value for public.breakfaith_all.gender
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.age
     *
     * @return the value of public.breakfaith_all.age
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.age
     *
     * @param age the value for public.breakfaith_all.age
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.judges
     *
     * @return the value of public.breakfaith_all.judges
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getJudges() {
        return judges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.judges
     *
     * @param judges the value for public.breakfaith_all.judges
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setJudges(String judges) {
        this.judges = judges == null ? null : judges.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.liability
     *
     * @return the value of public.breakfaith_all.liability
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getLiability() {
        return liability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.liability
     *
     * @param liability the value for public.breakfaith_all.liability
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setLiability(String liability) {
        this.liability = liability == null ? null : liability.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.org_code
     *
     * @return the value of public.breakfaith_all.org_code
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.org_code
     *
     * @param orgCode the value for public.breakfaith_all.org_code
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.performance
     *
     * @return the value of public.breakfaith_all.performance
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getPerformance() {
        return performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.performance
     *
     * @param performance the value for public.breakfaith_all.performance
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setPerformance(String performance) {
        this.performance = performance == null ? null : performance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.person_name
     *
     * @return the value of public.breakfaith_all.person_name
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.person_name
     *
     * @param personName the value for public.breakfaith_all.person_name
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.rep_name
     *
     * @return the value of public.breakfaith_all.rep_name
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getRepName() {
        return repName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.rep_name
     *
     * @param repName the value for public.breakfaith_all.rep_name
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setRepName(String repName) {
        this.repName = repName == null ? null : repName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.source
     *
     * @return the value of public.breakfaith_all.source
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.source
     *
     * @param source the value for public.breakfaith_all.source
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.summary
     *
     * @return the value of public.breakfaith_all.summary
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.summary
     *
     * @param summary the value for public.breakfaith_all.summary
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.flag
     *
     * @return the value of public.breakfaith_all.flag
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.flag
     *
     * @param flag the value for public.breakfaith_all.flag
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.publish_date
     *
     * @return the value of public.breakfaith_all.publish_date
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.publish_date
     *
     * @param publishDate the value for public.breakfaith_all.publish_date
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.open_time
     *
     * @return the value of public.breakfaith_all.open_time
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.open_time
     *
     * @param openTime the value for public.breakfaith_all.open_time
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.modify_date
     *
     * @return the value of public.breakfaith_all.modify_date
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.modify_date
     *
     * @param modifyDate the value for public.breakfaith_all.modify_date
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.collect_date
     *
     * @return the value of public.breakfaith_all.collect_date
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getCollectDate() {
        return collectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.collect_date
     *
     * @param collectDate the value for public.breakfaith_all.collect_date
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCollectDate(Date collectDate) {
        this.collectDate = collectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.create_time
     *
     * @return the value of public.breakfaith_all.create_time
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.create_time
     *
     * @param createTime the value for public.breakfaith_all.create_time
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.breakfaith_all.update_time
     *
     * @return the value of public.breakfaith_all.update_time
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.breakfaith_all.update_time
     *
     * @param updateTime the value for public.breakfaith_all.update_time
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
