package com.masspick.peak.model.legal;

import java.util.Date;

/**
 * CrdCourtDp
 */
public class CrdCourtDp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_court_dp.id
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_court_dp.name
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_court_dp.type
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_court_dp.court_id
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    private String courtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_court_dp.create_time
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_court_dp.update_time
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_court_dp.id
     *
     * @return the value of public.crd_court_dp.id
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_court_dp.id
     *
     * @param id the value for public.crd_court_dp.id
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_court_dp.name
     *
     * @return the value of public.crd_court_dp.name
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_court_dp.name
     *
     * @param name the value for public.crd_court_dp.name
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_court_dp.type
     *
     * @return the value of public.crd_court_dp.type
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_court_dp.type
     *
     * @param type the value for public.crd_court_dp.type
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_court_dp.court_id
     *
     * @return the value of public.crd_court_dp.court_id
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public String getCourtId() {
        return courtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_court_dp.court_id
     *
     * @param courtId the value for public.crd_court_dp.court_id
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public void setCourtId(String courtId) {
        this.courtId = courtId == null ? null : courtId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_court_dp.create_time
     *
     * @return the value of public.crd_court_dp.create_time
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_court_dp.create_time
     *
     * @param createTime the value for public.crd_court_dp.create_time
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_court_dp.update_time
     *
     * @return the value of public.crd_court_dp.update_time
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_court_dp.update_time
     *
     * @param updateTime the value for public.crd_court_dp.update_time
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
