package com.masspick.peak.model.legal;

import java.util.Date;

/**
 * CrdClient
 */
public class CrdClient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_client.id
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_client.name
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_client.courtpub_id
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    private String courtpubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_client.create_time
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.crd_client.update_time
     *
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_client.id
     *
     * @return the value of public.crd_client.id
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_client.id
     *
     * @param id the value for public.crd_client.id
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_client.name
     *
     * @return the value of public.crd_client.name
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_client.name
     *
     * @param name the value for public.crd_client.name
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_client.courtpub_id
     *
     * @return the value of public.crd_client.courtpub_id
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public String getCourtpubId() {
        return courtpubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_client.courtpub_id
     *
     * @param courtpubId the value for public.crd_client.courtpub_id
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public void setCourtpubId(String courtpubId) {
        this.courtpubId = courtpubId == null ? null : courtpubId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_client.create_time
     *
     * @return the value of public.crd_client.create_time
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_client.create_time
     *
     * @param createTime the value for public.crd_client.create_time
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.crd_client.update_time
     *
     * @return the value of public.crd_client.update_time
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.crd_client.update_time
     *
     * @param updateTime the value for public.crd_client.update_time
     * @mbggenerated Mon Jun 11 19:05:06 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
