package com.masspick.peak.model.legal;

import java.util.Date;

/**
 * Executed
 */
public class Executed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.id
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.case_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String caseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.court_name
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String courtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.case_state
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String caseState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.province
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.city
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.area
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.catalog
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String catalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.clients
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String clients;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.data_from
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Integer dataFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.detail_link
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String detailLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.executed
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String executed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.id_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String idNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.judges
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String judges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.org_code
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.source
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.subject_matter
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String subjectMatter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.summary
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.open_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.modify_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.collect_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date collectTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.flag
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.create_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.update_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.gist_id
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String gistId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.court_url
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String courtUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.trial_url
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String trialUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.executed_all.key
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String key;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.id
     *
     * @return the value of public.executed_all.id
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.id
     *
     * @param id the value for public.executed_all.id
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.case_num
     *
     * @return the value of public.executed_all.case_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCaseNum() {
        return caseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.case_num
     *
     * @param caseNum the value for public.executed_all.case_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCaseNum(String caseNum) {
        this.caseNum = caseNum == null ? null : caseNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.court_name
     *
     * @return the value of public.executed_all.court_name
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCourtName() {
        return courtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.court_name
     *
     * @param courtName the value for public.executed_all.court_name
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCourtName(String courtName) {
        this.courtName = courtName == null ? null : courtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.case_state
     *
     * @return the value of public.executed_all.case_state
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCaseState() {
        return caseState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.case_state
     *
     * @param caseState the value for public.executed_all.case_state
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCaseState(String caseState) {
        this.caseState = caseState == null ? null : caseState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.province
     *
     * @return the value of public.executed_all.province
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.province
     *
     * @param province the value for public.executed_all.province
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.city
     *
     * @return the value of public.executed_all.city
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.city
     *
     * @param city the value for public.executed_all.city
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.area
     *
     * @return the value of public.executed_all.area
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.area
     *
     * @param area the value for public.executed_all.area
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.catalog
     *
     * @return the value of public.executed_all.catalog
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.catalog
     *
     * @param catalog the value for public.executed_all.catalog
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog == null ? null : catalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.clients
     *
     * @return the value of public.executed_all.clients
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getClients() {
        return clients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.clients
     *
     * @param clients the value for public.executed_all.clients
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setClients(String clients) {
        this.clients = clients == null ? null : clients.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.data_from
     *
     * @return the value of public.executed_all.data_from
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Integer getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.data_from
     *
     * @param dataFrom the value for public.executed_all.data_from
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setDataFrom(Integer dataFrom) {
        this.dataFrom = dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.detail_link
     *
     * @return the value of public.executed_all.detail_link
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getDetailLink() {
        return detailLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.detail_link
     *
     * @param detailLink the value for public.executed_all.detail_link
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setDetailLink(String detailLink) {
        this.detailLink = detailLink == null ? null : detailLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.executed
     *
     * @return the value of public.executed_all.executed
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getExecuted() {
        return executed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.executed
     *
     * @param executed the value for public.executed_all.executed
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setExecuted(String executed) {
        this.executed = executed == null ? null : executed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.id_num
     *
     * @return the value of public.executed_all.id_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.id_num
     *
     * @param idNum the value for public.executed_all.id_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum == null ? null : idNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.judges
     *
     * @return the value of public.executed_all.judges
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getJudges() {
        return judges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.judges
     *
     * @param judges the value for public.executed_all.judges
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setJudges(String judges) {
        this.judges = judges == null ? null : judges.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.org_code
     *
     * @return the value of public.executed_all.org_code
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.org_code
     *
     * @param orgCode the value for public.executed_all.org_code
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.source
     *
     * @return the value of public.executed_all.source
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.source
     *
     * @param source the value for public.executed_all.source
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.subject_matter
     *
     * @return the value of public.executed_all.subject_matter
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getSubjectMatter() {
        return subjectMatter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.subject_matter
     *
     * @param subjectMatter the value for public.executed_all.subject_matter
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setSubjectMatter(String subjectMatter) {
        this.subjectMatter = subjectMatter == null ? null : subjectMatter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.summary
     *
     * @return the value of public.executed_all.summary
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.summary
     *
     * @param summary the value for public.executed_all.summary
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.open_time
     *
     * @return the value of public.executed_all.open_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.open_time
     *
     * @param openTime the value for public.executed_all.open_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.modify_date
     *
     * @return the value of public.executed_all.modify_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.modify_date
     *
     * @param modifyDate the value for public.executed_all.modify_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.collect_time
     *
     * @return the value of public.executed_all.collect_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.collect_time
     *
     * @param collectTime the value for public.executed_all.collect_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.flag
     *
     * @return the value of public.executed_all.flag
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.flag
     *
     * @param flag the value for public.executed_all.flag
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.create_time
     *
     * @return the value of public.executed_all.create_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.create_time
     *
     * @param createTime the value for public.executed_all.create_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.update_time
     *
     * @return the value of public.executed_all.update_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.update_time
     *
     * @param updateTime the value for public.executed_all.update_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.gist_id
     *
     * @return the value of public.executed_all.gist_id
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getGistId() {
        return gistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.gist_id
     *
     * @param gistId the value for public.executed_all.gist_id
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setGistId(String gistId) {
        this.gistId = gistId == null ? null : gistId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.court_url
     *
     * @return the value of public.executed_all.court_url
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCourtUrl() {
        return courtUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.court_url
     *
     * @param courtUrl the value for public.executed_all.court_url
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCourtUrl(String courtUrl) {
        this.courtUrl = courtUrl == null ? null : courtUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.trial_url
     *
     * @return the value of public.executed_all.trial_url
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getTrialUrl() {
        return trialUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.trial_url
     *
     * @param trialUrl the value for public.executed_all.trial_url
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setTrialUrl(String trialUrl) {
        this.trialUrl = trialUrl == null ? null : trialUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.executed_all.key
     *
     * @return the value of public.executed_all.key
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.executed_all.key
     *
     * @param key the value for public.executed_all.key
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }
}
