version: '3'
services:
  interface:
    image: ccr.ccs.tencentyun.com/bjd_bigdata/peak-interface:${VERSION}
    ports:
      - "9500:8080"
    environment:
      - EUREKA_MEMBERS=http://eureka1:8761/eureka,http://eureka2:8761/eureka,http://eureka3:8761/eureka
      - SPRING_PREFER_NETWORK=10.0.100
      - ENV=prod
    networks:
      springcloud-overlay:
        aliases:
          - peakInterface
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay