package com.masspick.peak.model.dto.legal;

import java.util.Date;

/**
 * Created by admin on 2018/7/6 0006.
 */
public class CourtDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.id
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.title
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.case_cause
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String caseCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.approval_reslut
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String approvalReslut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.approval_type
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String approvalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.province
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.city
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.area
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.case_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String caseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.catalog
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String catalog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.clients
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String clients;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.court_lev
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String courtLev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.court_name
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String courtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.data_from
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Integer dataFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.defendant
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String defendant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.detail_link
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String detailLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.judges
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String judges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.law_office_d
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String lawOfficeD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.law_office_p
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String lawOfficeP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.laws
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String laws;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.lawyer_d
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String lawyerD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.path
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.plaintiff
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String plaintiff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.source
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.suit_type
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String suitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.summary
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.type1
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String type1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.type2
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String type2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.type3
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String type3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.type4
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String type4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.type5
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String type5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.writ_type
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String writType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.approval
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String approval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.approval_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date approvalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.approval_date_y
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String approvalDateY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.approval_date_y_m
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String approvalDateYM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.suit_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date suitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.publish_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.collect_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date collectDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.modify_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.flag
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.create_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.update_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.court_all.html
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    private String html;

    /**
     * etpId
     */
    private String etpId;

    /**
     * text
     */
    private String text;

    /**
     * Gets etpId
     *
     * @return value of etpId
     */
    public String getEtpId() {
        return etpId;
    }

    /**
     * @param etpId
     */
    public void setEtpId(String etpId) {
        this.etpId = etpId;
    }

    /**
     * Gets text
     *
     * @return value of text
     */
    public String getText() {
        return text;
    }

    /**
     * @param text
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.id
     *
     * @return the value of public.court_all.id
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.id
     *
     * @param id the value for public.court_all.id
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.title
     *
     * @return the value of public.court_all.title
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.title
     *
     * @param title the value for public.court_all.title
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.case_cause
     *
     * @return the value of public.court_all.case_cause
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCaseCause() {
        return caseCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.case_cause
     *
     * @param caseCause the value for public.court_all.case_cause
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCaseCause(String caseCause) {
        this.caseCause = caseCause == null ? null : caseCause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.approval_reslut
     *
     * @return the value of public.court_all.approval_reslut
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getApprovalReslut() {
        return approvalReslut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.approval_reslut
     *
     * @param approvalReslut the value for public.court_all.approval_reslut
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setApprovalReslut(String approvalReslut) {
        this.approvalReslut = approvalReslut == null ? null : approvalReslut.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.approval_type
     *
     * @return the value of public.court_all.approval_type
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getApprovalType() {
        return approvalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.approval_type
     *
     * @param approvalType the value for public.court_all.approval_type
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setApprovalType(String approvalType) {
        this.approvalType = approvalType == null ? null : approvalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.province
     *
     * @return the value of public.court_all.province
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.province
     *
     * @param province the value for public.court_all.province
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.city
     *
     * @return the value of public.court_all.city
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.city
     *
     * @param city the value for public.court_all.city
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.area
     *
     * @return the value of public.court_all.area
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.area
     *
     * @param area the value for public.court_all.area
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.case_num
     *
     * @return the value of public.court_all.case_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCaseNum() {
        return caseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.case_num
     *
     * @param caseNum the value for public.court_all.case_num
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCaseNum(String caseNum) {
        this.caseNum = caseNum == null ? null : caseNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.catalog
     *
     * @return the value of public.court_all.catalog
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.catalog
     *
     * @param catalog the value for public.court_all.catalog
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog == null ? null : catalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.clients
     *
     * @return the value of public.court_all.clients
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getClients() {
        return clients;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.clients
     *
     * @param clients the value for public.court_all.clients
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setClients(String clients) {
        this.clients = clients == null ? null : clients.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.court_lev
     *
     * @return the value of public.court_all.court_lev
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCourtLev() {
        return courtLev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.court_lev
     *
     * @param courtLev the value for public.court_all.court_lev
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCourtLev(String courtLev) {
        this.courtLev = courtLev == null ? null : courtLev.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.court_name
     *
     * @return the value of public.court_all.court_name
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getCourtName() {
        return courtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.court_name
     *
     * @param courtName the value for public.court_all.court_name
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCourtName(String courtName) {
        this.courtName = courtName == null ? null : courtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.data_from
     *
     * @return the value of public.court_all.data_from
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Integer getDataFrom() {
        return dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.data_from
     *
     * @param dataFrom the value for public.court_all.data_from
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setDataFrom(Integer dataFrom) {
        this.dataFrom = dataFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.defendant
     *
     * @return the value of public.court_all.defendant
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getDefendant() {
        return defendant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.defendant
     *
     * @param defendant the value for public.court_all.defendant
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setDefendant(String defendant) {
        this.defendant = defendant == null ? null : defendant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.detail_link
     *
     * @return the value of public.court_all.detail_link
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getDetailLink() {
        return detailLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.detail_link
     *
     * @param detailLink the value for public.court_all.detail_link
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setDetailLink(String detailLink) {
        this.detailLink = detailLink == null ? null : detailLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.judges
     *
     * @return the value of public.court_all.judges
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getJudges() {
        return judges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.judges
     *
     * @param judges the value for public.court_all.judges
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setJudges(String judges) {
        this.judges = judges == null ? null : judges.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.law_office_d
     *
     * @return the value of public.court_all.law_office_d
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getLawOfficeD() {
        return lawOfficeD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.law_office_d
     *
     * @param lawOfficeD the value for public.court_all.law_office_d
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setLawOfficeD(String lawOfficeD) {
        this.lawOfficeD = lawOfficeD == null ? null : lawOfficeD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.law_office_p
     *
     * @return the value of public.court_all.law_office_p
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getLawOfficeP() {
        return lawOfficeP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.law_office_p
     *
     * @param lawOfficeP the value for public.court_all.law_office_p
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setLawOfficeP(String lawOfficeP) {
        this.lawOfficeP = lawOfficeP == null ? null : lawOfficeP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.laws
     *
     * @return the value of public.court_all.laws
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getLaws() {
        return laws;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.laws
     *
     * @param laws the value for public.court_all.laws
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setLaws(String laws) {
        this.laws = laws == null ? null : laws.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.lawyer_d
     *
     * @return the value of public.court_all.lawyer_d
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getLawyerD() {
        return lawyerD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.lawyer_d
     *
     * @param lawyerD the value for public.court_all.lawyer_d
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setLawyerD(String lawyerD) {
        this.lawyerD = lawyerD == null ? null : lawyerD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.path
     *
     * @return the value of public.court_all.path
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.path
     *
     * @param path the value for public.court_all.path
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.plaintiff
     *
     * @return the value of public.court_all.plaintiff
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getPlaintiff() {
        return plaintiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.plaintiff
     *
     * @param plaintiff the value for public.court_all.plaintiff
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setPlaintiff(String plaintiff) {
        this.plaintiff = plaintiff == null ? null : plaintiff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.source
     *
     * @return the value of public.court_all.source
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.source
     *
     * @param source the value for public.court_all.source
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.suit_type
     *
     * @return the value of public.court_all.suit_type
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getSuitType() {
        return suitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.suit_type
     *
     * @param suitType the value for public.court_all.suit_type
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setSuitType(String suitType) {
        this.suitType = suitType == null ? null : suitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.summary
     *
     * @return the value of public.court_all.summary
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.summary
     *
     * @param summary the value for public.court_all.summary
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.type1
     *
     * @return the value of public.court_all.type1
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getType1() {
        return type1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.type1
     *
     * @param type1 the value for public.court_all.type1
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setType1(String type1) {
        this.type1 = type1 == null ? null : type1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.type2
     *
     * @return the value of public.court_all.type2
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getType2() {
        return type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.type2
     *
     * @param type2 the value for public.court_all.type2
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setType2(String type2) {
        this.type2 = type2 == null ? null : type2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.type3
     *
     * @return the value of public.court_all.type3
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getType3() {
        return type3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.type3
     *
     * @param type3 the value for public.court_all.type3
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setType3(String type3) {
        this.type3 = type3 == null ? null : type3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.type4
     *
     * @return the value of public.court_all.type4
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getType4() {
        return type4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.type4
     *
     * @param type4 the value for public.court_all.type4
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setType4(String type4) {
        this.type4 = type4 == null ? null : type4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.type5
     *
     * @return the value of public.court_all.type5
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getType5() {
        return type5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.type5
     *
     * @param type5 the value for public.court_all.type5
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setType5(String type5) {
        this.type5 = type5 == null ? null : type5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.writ_type
     *
     * @return the value of public.court_all.writ_type
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getWritType() {
        return writType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.writ_type
     *
     * @param writType the value for public.court_all.writ_type
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setWritType(String writType) {
        this.writType = writType == null ? null : writType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.approval
     *
     * @return the value of public.court_all.approval
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getApproval() {
        return approval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.approval
     *
     * @param approval the value for public.court_all.approval
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setApproval(String approval) {
        this.approval = approval == null ? null : approval.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.approval_date
     *
     * @return the value of public.court_all.approval_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getApprovalDate() {
        return approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.approval_date
     *
     * @param approvalDate the value for public.court_all.approval_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.approval_date_y
     *
     * @return the value of public.court_all.approval_date_y
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getApprovalDateY() {
        return approvalDateY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.approval_date_y
     *
     * @param approvalDateY the value for public.court_all.approval_date_y
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setApprovalDateY(String approvalDateY) {
        this.approvalDateY = approvalDateY == null ? null : approvalDateY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.approval_date_y_m
     *
     * @return the value of public.court_all.approval_date_y_m
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getApprovalDateYM() {
        return approvalDateYM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.approval_date_y_m
     *
     * @param approvalDateYM the value for public.court_all.approval_date_y_m
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setApprovalDateYM(String approvalDateYM) {
        this.approvalDateYM = approvalDateYM == null ? null : approvalDateYM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.suit_date
     *
     * @return the value of public.court_all.suit_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getSuitDate() {
        return suitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.suit_date
     *
     * @param suitDate the value for public.court_all.suit_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setSuitDate(Date suitDate) {
        this.suitDate = suitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.publish_date
     *
     * @return the value of public.court_all.publish_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.publish_date
     *
     * @param publishDate the value for public.court_all.publish_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.collect_date
     *
     * @return the value of public.court_all.collect_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getCollectDate() {
        return collectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.collect_date
     *
     * @param collectDate the value for public.court_all.collect_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCollectDate(Date collectDate) {
        this.collectDate = collectDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.modify_date
     *
     * @return the value of public.court_all.modify_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.modify_date
     *
     * @param modifyDate the value for public.court_all.modify_date
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.flag
     *
     * @return the value of public.court_all.flag
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.flag
     *
     * @param flag the value for public.court_all.flag
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.create_time
     *
     * @return the value of public.court_all.create_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.create_time
     *
     * @param createTime the value for public.court_all.create_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.update_time
     *
     * @return the value of public.court_all.update_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.update_time
     *
     * @param updateTime the value for public.court_all.update_time
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.court_all.html
     *
     * @return the value of public.court_all.html
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public String getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.court_all.html
     *
     * @param html the value for public.court_all.html
     *
     * @mbggenerated Mon Jun 11 17:25:04 CST 2018
     */
    public void setHtml(String html) {
        this.html = html == null ? null : html.trim();
    }
}
