server:
  port: 8080
logging:
  level:
      com.masspick.peak.guest.mapper: debug


spring:
  application:
    name: peak-decision-client
  datasource:
    url: jdbc:mysql://192.168.111.210:3306/peak_decision?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_MEMBERS}
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}




