version: '3'
services:
  admin:
    image: ccr.ccs.tencentyun.com/bjd_bigdata/peak-flow:${VERSION}
    environment:
      - EUREKA_MEMBERS=http://eureka1:8761/eureka,http://eureka2:8761/eureka,http://eureka3:8761/eureka
      - ENV=prod
      - JDBC_URL=192.168.0.55
      - JDBC_PORT=3306
      - JDBC_USERNAME=root
      - JDBC_PASSWORD=${JDBC_PASSWORD}
      - SPRING_PREFER_NETWORK=10.0.0
    networks:
      springcloud-overlay:
        aliases:
          - peakFlowAdmin
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay
