package com.masspick.peak.model.dto.tax;

/**
 * TaxDeclareInfo
 */
public class TaxDeclareInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.declare_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String declareDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.declare_term_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String declareTermDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.tax_start_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String taxStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.tax_end_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String taxEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.collect_item
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String collectItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.total_income
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double totalIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.base_tax
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double baseTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.tax_rate
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double taxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.payable_tax
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double payableTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.paid_tax
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double paidTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.overpay_tax
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double overpayTax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.voucher_type
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String voucherType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.cancel_sign
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String cancelSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.cancel_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String cancelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_declare_info.reduce_tax
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double reduceTax;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_declare_info.id
     *
     * @return the value of tax_declare_info.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_declare_info.id
     *
     * @param id the value for tax_declare_info.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * Gets declareDate
     *
     * @return value of declareDate
     */
    public String getDeclareDate() {
        return declareDate;
    }

    /**
     * @param declareDate
     */
    public void setDeclareDate(String declareDate) {
        this.declareDate = declareDate;
    }

    /**
     * Gets declareTermDate
     *
     * @return value of declareTermDate
     */
    public String getDeclareTermDate() {
        return declareTermDate;
    }

    /**
     * @param declareTermDate
     */
    public void setDeclareTermDate(String declareTermDate) {
        this.declareTermDate = declareTermDate;
    }

    /**
     * Gets taxStartDate
     *
     * @return value of taxStartDate
     */
    public String getTaxStartDate() {
        return taxStartDate;
    }

    /**
     * @param taxStartDate
     */
    public void setTaxStartDate(String taxStartDate) {
        this.taxStartDate = taxStartDate;
    }

    /**
     * Gets taxEndDate
     *
     * @return value of taxEndDate
     */
    public String getTaxEndDate() {
        return taxEndDate;
    }

    /**
     * @param taxEndDate
     */
    public void setTaxEndDate(String taxEndDate) {
        this.taxEndDate = taxEndDate;
    }

    /**
     * Gets collectItem
     *
     * @return value of collectItem
     */
    public String getCollectItem() {
        return collectItem;
    }

    /**
     * @param collectItem
     */
    public void setCollectItem(String collectItem) {
        this.collectItem = collectItem;
    }

    /**
     * Gets totalIncome
     *
     * @return value of totalIncome
     */
    public Double getTotalIncome() {
        return totalIncome;
    }

    /**
     * @param totalIncome
     */
    public void setTotalIncome(Double totalIncome) {
        this.totalIncome = totalIncome;
    }

    /**
     * Gets baseTax
     *
     * @return value of baseTax
     */
    public Double getBaseTax() {
        return baseTax;
    }

    /**
     * @param baseTax
     */
    public void setBaseTax(Double baseTax) {
        this.baseTax = baseTax;
    }

    /**
     * Gets taxRate
     *
     * @return value of taxRate
     */
    public Double getTaxRate() {
        return taxRate;
    }

    /**
     * @param taxRate
     */
    public void setTaxRate(Double taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * Gets payableTax
     *
     * @return value of payableTax
     */
    public Double getPayableTax() {
        return payableTax;
    }

    /**
     * @param payableTax
     */
    public void setPayableTax(Double payableTax) {
        this.payableTax = payableTax;
    }

    /**
     * Gets paidTax
     *
     * @return value of paidTax
     */
    public Double getPaidTax() {
        return paidTax;
    }

    /**
     * @param paidTax
     */
    public void setPaidTax(Double paidTax) {
        this.paidTax = paidTax;
    }

    /**
     * Gets overpayTax
     *
     * @return value of overpayTax
     */
    public Double getOverpayTax() {
        return overpayTax;
    }

    /**
     * @param overpayTax
     */
    public void setOverpayTax(Double overpayTax) {
        this.overpayTax = overpayTax;
    }

    /**
     * Gets voucherType
     *
     * @return value of voucherType
     */
    public String getVoucherType() {
        return voucherType;
    }

    /**
     * @param voucherType
     */
    public void setVoucherType(String voucherType) {
        this.voucherType = voucherType;
    }

    /**
     * Gets cancelSign
     *
     * @return value of cancelSign
     */
    public String getCancelSign() {
        return cancelSign;
    }

    /**
     * @param cancelSign
     */
    public void setCancelSign(String cancelSign) {
        this.cancelSign = cancelSign;
    }

    /**
     * Gets cancelDate
     *
     * @return value of cancelDate
     */
    public String getCancelDate() {
        return cancelDate;
    }

    /**
     * @param cancelDate
     */
    public void setCancelDate(String cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * Gets reduceTax
     *
     * @return value of reduceTax
     */
    public Double getReduceTax() {
        return reduceTax;
    }

    /**
     * @param reduceTax
     */
    public void setReduceTax(Double reduceTax) {
        this.reduceTax = reduceTax;
    }
}
