package com.masspick.peak.model.dto.tax;

/**
 * TaxProfitNormal
 */
public class TaxProfitNormal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_normal.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_normal.out_id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String outId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_normal.seq_no
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_normal.category
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_normal.last_term_fee
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double lastTermFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_normal.update_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_normal.term_fee
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double termFee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_normal.id
     *
     * @return the value of tax_profit_normal.id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_normal.id
     *
     * @param id the value for tax_profit_normal.id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_normal.out_id
     *
     * @return the value of tax_profit_normal.out_id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_normal.out_id
     *
     * @param outId the value for tax_profit_normal.out_id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_normal.seq_no
     *
     * @return the value of tax_profit_normal.seq_no
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_normal.seq_no
     *
     * @param seqNo the value for tax_profit_normal.seq_no
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo == null ? null : seqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_normal.category
     *
     * @return the value of tax_profit_normal.category
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_normal.category
     *
     * @param category the value for tax_profit_normal.category
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_normal.last_term_fee
     *
     * @return the value of tax_profit_normal.last_term_fee
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getLastTermFee() {
        return lastTermFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_normal.last_term_fee
     *
     * @param lastTermFee the value for tax_profit_normal.last_term_fee
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setLastTermFee(Double lastTermFee) {
        this.lastTermFee = lastTermFee;
    }


    /**
     * Gets updateDate
     *
     * @return value of updateDate
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * @param updateDate
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_normal.term_fee
     *
     * @return the value of tax_profit_normal.term_fee
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getTermFee() {
        return termFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_normal.term_fee
     *
     * @param termFee the value for tax_profit_normal.term_fee
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setTermFee(Double termFee) {
        this.termFee = termFee;
    }
}
