package com.masspick.peak.model.dto.tax;

/**
 * TaxProfitMirco
 */
public class TaxProfitMirco {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_mirco.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_mirco.year_fee
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double yearFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_mirco.month_fee
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double monthFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_mirco.category
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_mirco.update_date
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_mirco.out_id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String outId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_profit_mirco.seq_no
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String seqNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_mirco.id
     *
     * @return the value of tax_profit_mirco.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_mirco.id
     *
     * @param id the value for tax_profit_mirco.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_mirco.year_fee
     *
     * @return the value of tax_profit_mirco.year_fee
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getYearFee() {
        return yearFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_mirco.year_fee
     *
     * @param yearFee the value for tax_profit_mirco.year_fee
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setYearFee(Double yearFee) {
        this.yearFee = yearFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_mirco.month_fee
     *
     * @return the value of tax_profit_mirco.month_fee
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getMonthFee() {
        return monthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_mirco.month_fee
     *
     * @param monthFee the value for tax_profit_mirco.month_fee
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setMonthFee(Double monthFee) {
        this.monthFee = monthFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_mirco.category
     *
     * @return the value of tax_profit_mirco.category
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_mirco.category
     *
     * @param category the value for tax_profit_mirco.category
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }


    /**
     * Gets updateDate
     *
     * @return value of updateDate
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * @param updateDate
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_mirco.out_id
     *
     * @return the value of tax_profit_mirco.out_id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_mirco.out_id
     *
     * @param outId the value for tax_profit_mirco.out_id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_profit_mirco.seq_no
     *
     * @return the value of tax_profit_mirco.seq_no
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_profit_mirco.seq_no
     *
     * @param seqNo the value for tax_profit_mirco.seq_no
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo == null ? null : seqNo.trim();
    }
}
