package com.masspick.peak.model.dto.tax;

import java.util.Date;

/**
 * TaxRegInfo
 */
public class TaxRegInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.reg_id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String regId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.reg_name
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String regName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.org_id
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.address
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.prod_address
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String prodAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.buss_scope
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String bussScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.prod_phone
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String prodPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.reg_category
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String regCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.open_Time
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Date openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.business_start
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String businessStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.business_finish
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String businessFinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.reg_capital
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Double regCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.industry_code
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String industryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.industry_name
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String industryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.employer_count
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private Integer employerCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.reg_type_code
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String regTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.reg_type_name
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String regTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.reg_state
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String regState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.account_standard_name
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String accountStandardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.prod_postcode
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String prodPostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_reg_info.tax_office
     *
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    private String taxOffice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.id
     *
     * @return the value of tax_reg_info.id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.id
     *
     * @param id the value for tax_reg_info.id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.reg_id
     *
     * @return the value of tax_reg_info.reg_id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.reg_id
     *
     * @param regId the value for tax_reg_info.reg_id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.reg_name
     *
     * @return the value of tax_reg_info.reg_name
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getRegName() {
        return regName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.reg_name
     *
     * @param regName the value for tax_reg_info.reg_name
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setRegName(String regName) {
        this.regName = regName == null ? null : regName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.org_id
     *
     * @return the value of tax_reg_info.org_id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.org_id
     *
     * @param orgId the value for tax_reg_info.org_id
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.address
     *
     * @return the value of tax_reg_info.address
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.address
     *
     * @param address the value for tax_reg_info.address
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.prod_address
     *
     * @return the value of tax_reg_info.prod_address
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getProdAddress() {
        return prodAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.prod_address
     *
     * @param prodAddress the value for tax_reg_info.prod_address
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setProdAddress(String prodAddress) {
        this.prodAddress = prodAddress == null ? null : prodAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.buss_scope
     *
     * @return the value of tax_reg_info.buss_scope
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getBussScope() {
        return bussScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.buss_scope
     *
     * @param bussScope the value for tax_reg_info.buss_scope
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setBussScope(String bussScope) {
        this.bussScope = bussScope == null ? null : bussScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.prod_phone
     *
     * @return the value of tax_reg_info.prod_phone
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getProdPhone() {
        return prodPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.prod_phone
     *
     * @param prodPhone the value for tax_reg_info.prod_phone
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setProdPhone(String prodPhone) {
        this.prodPhone = prodPhone == null ? null : prodPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.reg_category
     *
     * @return the value of tax_reg_info.reg_category
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getRegCategory() {
        return regCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.reg_category
     *
     * @param regCategory the value for tax_reg_info.reg_category
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setRegCategory(String regCategory) {
        this.regCategory = regCategory == null ? null : regCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.open_Time
     *
     * @return the value of tax_reg_info.open_Time
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Date getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.open_Time
     *
     * @param openTime the value for tax_reg_info.open_Time
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    /**
     * Gets businessStart
     *
     * @return value of businessStart
     */
    public String getBusinessStart() {
        return businessStart;
    }

    /**
     * @param businessStart
     */
    public void setBusinessStart(String businessStart) {
        this.businessStart = businessStart;
    }

    /**
     * Gets businessFinish
     *
     * @return value of businessFinish
     */
    public String getBusinessFinish() {
        return businessFinish;
    }

    /**
     * @param businessFinish
     */
    public void setBusinessFinish(String businessFinish) {
        this.businessFinish = businessFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.reg_capital
     *
     * @return the value of tax_reg_info.reg_capital
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Double getRegCapital() {
        return regCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.reg_capital
     *
     * @param regCapital the value for tax_reg_info.reg_capital
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setRegCapital(Double regCapital) {
        this.regCapital = regCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.industry_code
     *
     * @return the value of tax_reg_info.industry_code
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.industry_code
     *
     * @param industryCode the value for tax_reg_info.industry_code
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setIndustryCode(String industryCode) {
        this.industryCode = industryCode == null ? null : industryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.industry_name
     *
     * @return the value of tax_reg_info.industry_name
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.industry_name
     *
     * @param industryName the value for tax_reg_info.industry_name
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName == null ? null : industryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.employer_count
     *
     * @return the value of tax_reg_info.employer_count
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public Integer getEmployerCount() {
        return employerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.employer_count
     *
     * @param employerCount the value for tax_reg_info.employer_count
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setEmployerCount(Integer employerCount) {
        this.employerCount = employerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.reg_type_code
     *
     * @return the value of tax_reg_info.reg_type_code
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getRegTypeCode() {
        return regTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.reg_type_code
     *
     * @param regTypeCode the value for tax_reg_info.reg_type_code
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setRegTypeCode(String regTypeCode) {
        this.regTypeCode = regTypeCode == null ? null : regTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.reg_type_name
     *
     * @return the value of tax_reg_info.reg_type_name
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getRegTypeName() {
        return regTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.reg_type_name
     *
     * @param regTypeName the value for tax_reg_info.reg_type_name
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setRegTypeName(String regTypeName) {
        this.regTypeName = regTypeName == null ? null : regTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.reg_state
     *
     * @return the value of tax_reg_info.reg_state
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getRegState() {
        return regState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.reg_state
     *
     * @param regState the value for tax_reg_info.reg_state
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setRegState(String regState) {
        this.regState = regState == null ? null : regState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.account_standard_name
     *
     * @return the value of tax_reg_info.account_standard_name
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getAccountStandardName() {
        return accountStandardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.account_standard_name
     *
     * @param accountStandardName the value for tax_reg_info.account_standard_name
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setAccountStandardName(String accountStandardName) {
        this.accountStandardName = accountStandardName == null ? null : accountStandardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.prod_postcode
     *
     * @return the value of tax_reg_info.prod_postcode
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getProdPostcode() {
        return prodPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.prod_postcode
     *
     * @param prodPostcode the value for tax_reg_info.prod_postcode
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setProdPostcode(String prodPostcode) {
        this.prodPostcode = prodPostcode == null ? null : prodPostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_reg_info.tax_office
     *
     * @return the value of tax_reg_info.tax_office
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public String getTaxOffice() {
        return taxOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_reg_info.tax_office
     *
     * @param taxOffice the value for tax_reg_info.tax_office
     * @mbggenerated Mon Jun 11 12:20:29 CST 2018
     */
    public void setTaxOffice(String taxOffice) {
        this.taxOffice = taxOffice == null ? null : taxOffice.trim();
    }
}
