package com.masspick.peak.model.etp;

import java.util.Date;

/**
 * EtpAbnormal
 */
public class EtpAbnormal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_abnormal_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_abnormal_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String etpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_abnormal_all.enrol_reason
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String enrolReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_abnormal_all.enrol_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date enrolDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_abnormal_all.enrol_office
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String enrolOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_abnormal_all.remove_reason
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String removeReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_abnormal_all.remove_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date removeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_abnormal_all.remove_office
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String removeOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_abnormal_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date crawlTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_abnormal_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String outId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_abnormal_all.id
     *
     * @return the value of public.etp_abnormal_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_abnormal_all.id
     *
     * @param id the value for public.etp_abnormal_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_abnormal_all.etp_id
     *
     * @return the value of public.etp_abnormal_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEtpId() {
        return etpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_abnormal_all.etp_id
     *
     * @param etpId the value for public.etp_abnormal_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEtpId(String etpId) {
        this.etpId = etpId == null ? null : etpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_abnormal_all.enrol_reason
     *
     * @return the value of public.etp_abnormal_all.enrol_reason
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEnrolReason() {
        return enrolReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_abnormal_all.enrol_reason
     *
     * @param enrolReason the value for public.etp_abnormal_all.enrol_reason
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEnrolReason(String enrolReason) {
        this.enrolReason = enrolReason == null ? null : enrolReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_abnormal_all.enrol_date
     *
     * @return the value of public.etp_abnormal_all.enrol_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getEnrolDate() {
        return enrolDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_abnormal_all.enrol_date
     *
     * @param enrolDate the value for public.etp_abnormal_all.enrol_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEnrolDate(Date enrolDate) {
        this.enrolDate = enrolDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_abnormal_all.enrol_office
     *
     * @return the value of public.etp_abnormal_all.enrol_office
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEnrolOffice() {
        return enrolOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_abnormal_all.enrol_office
     *
     * @param enrolOffice the value for public.etp_abnormal_all.enrol_office
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEnrolOffice(String enrolOffice) {
        this.enrolOffice = enrolOffice == null ? null : enrolOffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_abnormal_all.remove_reason
     *
     * @return the value of public.etp_abnormal_all.remove_reason
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRemoveReason() {
        return removeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_abnormal_all.remove_reason
     *
     * @param removeReason the value for public.etp_abnormal_all.remove_reason
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRemoveReason(String removeReason) {
        this.removeReason = removeReason == null ? null : removeReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_abnormal_all.remove_date
     *
     * @return the value of public.etp_abnormal_all.remove_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getRemoveDate() {
        return removeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_abnormal_all.remove_date
     *
     * @param removeDate the value for public.etp_abnormal_all.remove_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRemoveDate(Date removeDate) {
        this.removeDate = removeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_abnormal_all.remove_office
     *
     * @return the value of public.etp_abnormal_all.remove_office
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRemoveOffice() {
        return removeOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_abnormal_all.remove_office
     *
     * @param removeOffice the value for public.etp_abnormal_all.remove_office
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRemoveOffice(String removeOffice) {
        this.removeOffice = removeOffice == null ? null : removeOffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_abnormal_all.crawl_time
     *
     * @return the value of public.etp_abnormal_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_abnormal_all.crawl_time
     *
     * @param crawlTime the value for public.etp_abnormal_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_abnormal_all.out_id
     *
     * @return the value of public.etp_abnormal_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_abnormal_all.out_id
     *
     * @param outId the value for public.etp_abnormal_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }
}
