package com.masspick.peak.model.etp;

import java.util.Date;

/**
 * EtpBranch
 */
public class EtpBranch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_branch_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_branch_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String etpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_branch_all.branch_company
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String branchCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_branch_all.branch_reg_office
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String branchRegOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_branch_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date crawlTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_branch_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String outId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_branch_all.id
     *
     * @return the value of public.etp_branch_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_branch_all.id
     *
     * @param id the value for public.etp_branch_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_branch_all.etp_id
     *
     * @return the value of public.etp_branch_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEtpId() {
        return etpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_branch_all.etp_id
     *
     * @param etpId the value for public.etp_branch_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEtpId(String etpId) {
        this.etpId = etpId == null ? null : etpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_branch_all.branch_company
     *
     * @return the value of public.etp_branch_all.branch_company
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getBranchCompany() {
        return branchCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_branch_all.branch_company
     *
     * @param branchCompany the value for public.etp_branch_all.branch_company
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setBranchCompany(String branchCompany) {
        this.branchCompany = branchCompany == null ? null : branchCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_branch_all.branch_reg_office
     *
     * @return the value of public.etp_branch_all.branch_reg_office
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getBranchRegOffice() {
        return branchRegOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_branch_all.branch_reg_office
     *
     * @param branchRegOffice the value for public.etp_branch_all.branch_reg_office
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setBranchRegOffice(String branchRegOffice) {
        this.branchRegOffice = branchRegOffice == null ? null : branchRegOffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_branch_all.crawl_time
     *
     * @return the value of public.etp_branch_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_branch_all.crawl_time
     *
     * @param crawlTime the value for public.etp_branch_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_branch_all.out_id
     *
     * @return the value of public.etp_branch_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_branch_all.out_id
     *
     * @param outId the value for public.etp_branch_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }
}
