package com.masspick.peak.model.etp;

import java.util.Date;

/**
 * EtpBase
 */
public class EtpBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.ent_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String entName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.industry
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.industry_code
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Integer industryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.credit_code
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String creditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.legal_person
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String legalPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.reg_office
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String regOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.reg_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.cancel_reason
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String cancelReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.cancel_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date cancelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.type_cn
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String typeCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.reg_capital
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String regCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.business_start
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date businessStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.business_finish
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date businessFinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.check_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.reg_state_cn
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String regStateCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.reg_state
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String regState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.address
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.business_scope
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String businessScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String outId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.reg_capital_unit
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String regCapitalUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.revoke_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date revokeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.country_code
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.industry_category
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String industryCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.city_code
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.province_code
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.is_move
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String isMove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.province
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.city
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.area
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.lng
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.lat
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.create_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date crawlTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.phone
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.industry_category_code
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String industryCategoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_base_all.reg_no
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String regNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.id
     *
     * @return the value of public.etp_base_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.id
     *
     * @param id the value for public.etp_base_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.ent_name
     *
     * @return the value of public.etp_base_all.ent_name
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEntName() {
        return entName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.ent_name
     *
     * @param entName the value for public.etp_base_all.ent_name
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEntName(String entName) {
        this.entName = entName == null ? null : entName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.industry
     *
     * @return the value of public.etp_base_all.industry
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.industry
     *
     * @param industry the value for public.etp_base_all.industry
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.industry_code
     *
     * @return the value of public.etp_base_all.industry_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Integer getIndustryCode() {
        return industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.industry_code
     *
     * @param industryCode the value for public.etp_base_all.industry_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setIndustryCode(Integer industryCode) {
        this.industryCode = industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.credit_code
     *
     * @return the value of public.etp_base_all.credit_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.credit_code
     *
     * @param creditCode the value for public.etp_base_all.credit_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.legal_person
     *
     * @return the value of public.etp_base_all.legal_person
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.legal_person
     *
     * @param legalPerson the value for public.etp_base_all.legal_person
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.reg_office
     *
     * @return the value of public.etp_base_all.reg_office
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRegOffice() {
        return regOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.reg_office
     *
     * @param regOffice the value for public.etp_base_all.reg_office
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegOffice(String regOffice) {
        this.regOffice = regOffice == null ? null : regOffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.reg_date
     *
     * @return the value of public.etp_base_all.reg_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.reg_date
     *
     * @param regDate the value for public.etp_base_all.reg_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.cancel_reason
     *
     * @return the value of public.etp_base_all.cancel_reason
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.cancel_reason
     *
     * @param cancelReason the value for public.etp_base_all.cancel_reason
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.cancel_date
     *
     * @return the value of public.etp_base_all.cancel_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.cancel_date
     *
     * @param cancelDate the value for public.etp_base_all.cancel_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.type
     *
     * @return the value of public.etp_base_all.type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.type
     *
     * @param type the value for public.etp_base_all.type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.type_cn
     *
     * @return the value of public.etp_base_all.type_cn
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getTypeCn() {
        return typeCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.type_cn
     *
     * @param typeCn the value for public.etp_base_all.type_cn
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setTypeCn(String typeCn) {
        this.typeCn = typeCn == null ? null : typeCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.reg_capital
     *
     * @return the value of public.etp_base_all.reg_capital
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRegCapital() {
        return regCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.reg_capital
     *
     * @param regCapital the value for public.etp_base_all.reg_capital
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegCapital(String regCapital) {
        this.regCapital = regCapital == null ? null : regCapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.business_start
     *
     * @return the value of public.etp_base_all.business_start
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getBusinessStart() {
        return businessStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.business_start
     *
     * @param businessStart the value for public.etp_base_all.business_start
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setBusinessStart(Date businessStart) {
        this.businessStart = businessStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.business_finish
     *
     * @return the value of public.etp_base_all.business_finish
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getBusinessFinish() {
        return businessFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.business_finish
     *
     * @param businessFinish the value for public.etp_base_all.business_finish
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setBusinessFinish(Date businessFinish) {
        this.businessFinish = businessFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.check_date
     *
     * @return the value of public.etp_base_all.check_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.check_date
     *
     * @param checkDate the value for public.etp_base_all.check_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.reg_state_cn
     *
     * @return the value of public.etp_base_all.reg_state_cn
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRegStateCn() {
        return regStateCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.reg_state_cn
     *
     * @param regStateCn the value for public.etp_base_all.reg_state_cn
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegStateCn(String regStateCn) {
        this.regStateCn = regStateCn == null ? null : regStateCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.reg_state
     *
     * @return the value of public.etp_base_all.reg_state
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRegState() {
        return regState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.reg_state
     *
     * @param regState the value for public.etp_base_all.reg_state
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegState(String regState) {
        this.regState = regState == null ? null : regState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.address
     *
     * @return the value of public.etp_base_all.address
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.address
     *
     * @param address the value for public.etp_base_all.address
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.business_scope
     *
     * @return the value of public.etp_base_all.business_scope
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.business_scope
     *
     * @param businessScope the value for public.etp_base_all.business_scope
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.out_id
     *
     * @return the value of public.etp_base_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.out_id
     *
     * @param outId the value for public.etp_base_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.reg_capital_unit
     *
     * @return the value of public.etp_base_all.reg_capital_unit
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRegCapitalUnit() {
        return regCapitalUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.reg_capital_unit
     *
     * @param regCapitalUnit the value for public.etp_base_all.reg_capital_unit
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegCapitalUnit(String regCapitalUnit) {
        this.regCapitalUnit = regCapitalUnit == null ? null : regCapitalUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.revoke_date
     *
     * @return the value of public.etp_base_all.revoke_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getRevokeDate() {
        return revokeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.revoke_date
     *
     * @param revokeDate the value for public.etp_base_all.revoke_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRevokeDate(Date revokeDate) {
        this.revokeDate = revokeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.country_code
     *
     * @return the value of public.etp_base_all.country_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.country_code
     *
     * @param countryCode the value for public.etp_base_all.country_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.industry_category
     *
     * @return the value of public.etp_base_all.industry_category
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getIndustryCategory() {
        return industryCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.industry_category
     *
     * @param industryCategory the value for public.etp_base_all.industry_category
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setIndustryCategory(String industryCategory) {
        this.industryCategory = industryCategory == null ? null : industryCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.city_code
     *
     * @return the value of public.etp_base_all.city_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.city_code
     *
     * @param cityCode the value for public.etp_base_all.city_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.province_code
     *
     * @return the value of public.etp_base_all.province_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.province_code
     *
     * @param provinceCode the value for public.etp_base_all.province_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.is_move
     *
     * @return the value of public.etp_base_all.is_move
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getIsMove() {
        return isMove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.is_move
     *
     * @param isMove the value for public.etp_base_all.is_move
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setIsMove(String isMove) {
        this.isMove = isMove == null ? null : isMove.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.province
     *
     * @return the value of public.etp_base_all.province
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.province
     *
     * @param province the value for public.etp_base_all.province
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.city
     *
     * @return the value of public.etp_base_all.city
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.city
     *
     * @param city the value for public.etp_base_all.city
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.area
     *
     * @return the value of public.etp_base_all.area
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.area
     *
     * @param area the value for public.etp_base_all.area
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.lng
     *
     * @return the value of public.etp_base_all.lng
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.lng
     *
     * @param lng the value for public.etp_base_all.lng
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.lat
     *
     * @return the value of public.etp_base_all.lat
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.lat
     *
     * @param lat the value for public.etp_base_all.lat
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.create_date
     *
     * @return the value of public.etp_base_all.create_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.create_date
     *
     * @param createDate the value for public.etp_base_all.create_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.crawl_time
     *
     * @return the value of public.etp_base_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.crawl_time
     *
     * @param crawlTime the value for public.etp_base_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.phone
     *
     * @return the value of public.etp_base_all.phone
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.phone
     *
     * @param phone the value for public.etp_base_all.phone
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.industry_category_code
     *
     * @return the value of public.etp_base_all.industry_category_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getIndustryCategoryCode() {
        return industryCategoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.industry_category_code
     *
     * @param industryCategoryCode the value for public.etp_base_all.industry_category_code
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setIndustryCategoryCode(String industryCategoryCode) {
        this.industryCategoryCode = industryCategoryCode == null ? null : industryCategoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_base_all.reg_no
     *
     * @return the value of public.etp_base_all.reg_no
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRegNo() {
        return regNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_base_all.reg_no
     *
     * @param regNo the value for public.etp_base_all.reg_no
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegNo(String regNo) {
        this.regNo = regNo == null ? null : regNo.trim();
    }
}
