package com.masspick.peak.model.etp;

import java.math.BigDecimal;
import java.util.Date;

/**
 * EtpChattel
 */
public class EtpChattel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String etpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.reg_number
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String regNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.record_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.reg_office
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String regOffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.be_guaranteed_amount
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private BigDecimal beGuaranteedAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.money_unit
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String moneyUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.state
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.public_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date publicDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.detail
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String outId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.cancel_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date cancelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.cancel_reason
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String cancelReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.type_cn
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String typeCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_chattel_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date crawlTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.id
     *
     * @return the value of public.etp_chattel_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.id
     *
     * @param id the value for public.etp_chattel_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.etp_id
     *
     * @return the value of public.etp_chattel_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEtpId() {
        return etpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.etp_id
     *
     * @param etpId the value for public.etp_chattel_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEtpId(String etpId) {
        this.etpId = etpId == null ? null : etpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.reg_number
     *
     * @return the value of public.etp_chattel_all.reg_number
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRegNumber() {
        return regNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.reg_number
     *
     * @param regNumber the value for public.etp_chattel_all.reg_number
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegNumber(String regNumber) {
        this.regNumber = regNumber == null ? null : regNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.record_date
     *
     * @return the value of public.etp_chattel_all.record_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.record_date
     *
     * @param recordDate the value for public.etp_chattel_all.record_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.reg_office
     *
     * @return the value of public.etp_chattel_all.reg_office
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRegOffice() {
        return regOffice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.reg_office
     *
     * @param regOffice the value for public.etp_chattel_all.reg_office
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegOffice(String regOffice) {
        this.regOffice = regOffice == null ? null : regOffice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.be_guaranteed_amount
     *
     * @return the value of public.etp_chattel_all.be_guaranteed_amount
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public BigDecimal getBeGuaranteedAmount() {
        return beGuaranteedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.be_guaranteed_amount
     *
     * @param beGuaranteedAmount the value for public.etp_chattel_all.be_guaranteed_amount
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setBeGuaranteedAmount(BigDecimal beGuaranteedAmount) {
        this.beGuaranteedAmount = beGuaranteedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.money_unit
     *
     * @return the value of public.etp_chattel_all.money_unit
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getMoneyUnit() {
        return moneyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.money_unit
     *
     * @param moneyUnit the value for public.etp_chattel_all.money_unit
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setMoneyUnit(String moneyUnit) {
        this.moneyUnit = moneyUnit == null ? null : moneyUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.state
     *
     * @return the value of public.etp_chattel_all.state
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.state
     *
     * @param state the value for public.etp_chattel_all.state
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.public_date
     *
     * @return the value of public.etp_chattel_all.public_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getPublicDate() {
        return publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.public_date
     *
     * @param publicDate the value for public.etp_chattel_all.public_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPublicDate(Date publicDate) {
        this.publicDate = publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.detail
     *
     * @return the value of public.etp_chattel_all.detail
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.detail
     *
     * @param detail the value for public.etp_chattel_all.detail
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.out_id
     *
     * @return the value of public.etp_chattel_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.out_id
     *
     * @param outId the value for public.etp_chattel_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.cancel_date
     *
     * @return the value of public.etp_chattel_all.cancel_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.cancel_date
     *
     * @param cancelDate the value for public.etp_chattel_all.cancel_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.cancel_reason
     *
     * @return the value of public.etp_chattel_all.cancel_reason
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.cancel_reason
     *
     * @param cancelReason the value for public.etp_chattel_all.cancel_reason
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason == null ? null : cancelReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.type_cn
     *
     * @return the value of public.etp_chattel_all.type_cn
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getTypeCn() {
        return typeCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.type_cn
     *
     * @param typeCn the value for public.etp_chattel_all.type_cn
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setTypeCn(String typeCn) {
        this.typeCn = typeCn == null ? null : typeCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_chattel_all.crawl_time
     *
     * @return the value of public.etp_chattel_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_chattel_all.crawl_time
     *
     * @param crawlTime the value for public.etp_chattel_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }
}
