package com.masspick.peak.model.etp;

import java.util.Date;

/**
 * EtpIll
 */
public class EtpIll {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_ill_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_ill_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String etpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_ill_all.decide_org
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String decideOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_ill_all.decide_main_fact
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String decideMainFact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_ill_all.enrol_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date enrolDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_ill_all.remove_org
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String removeOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_ill_all.remove_main_fact
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String removeMainFact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_ill_all.remove_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date removeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_ill_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date crawlTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_ill_all.id
     *
     * @return the value of public.etp_ill_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_ill_all.id
     *
     * @param id the value for public.etp_ill_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_ill_all.etp_id
     *
     * @return the value of public.etp_ill_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEtpId() {
        return etpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_ill_all.etp_id
     *
     * @param etpId the value for public.etp_ill_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEtpId(String etpId) {
        this.etpId = etpId == null ? null : etpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_ill_all.decide_org
     *
     * @return the value of public.etp_ill_all.decide_org
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getDecideOrg() {
        return decideOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_ill_all.decide_org
     *
     * @param decideOrg the value for public.etp_ill_all.decide_org
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setDecideOrg(String decideOrg) {
        this.decideOrg = decideOrg == null ? null : decideOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_ill_all.decide_main_fact
     *
     * @return the value of public.etp_ill_all.decide_main_fact
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getDecideMainFact() {
        return decideMainFact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_ill_all.decide_main_fact
     *
     * @param decideMainFact the value for public.etp_ill_all.decide_main_fact
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setDecideMainFact(String decideMainFact) {
        this.decideMainFact = decideMainFact == null ? null : decideMainFact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_ill_all.enrol_date
     *
     * @return the value of public.etp_ill_all.enrol_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getEnrolDate() {
        return enrolDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_ill_all.enrol_date
     *
     * @param enrolDate the value for public.etp_ill_all.enrol_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEnrolDate(Date enrolDate) {
        this.enrolDate = enrolDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_ill_all.remove_org
     *
     * @return the value of public.etp_ill_all.remove_org
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRemoveOrg() {
        return removeOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_ill_all.remove_org
     *
     * @param removeOrg the value for public.etp_ill_all.remove_org
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRemoveOrg(String removeOrg) {
        this.removeOrg = removeOrg == null ? null : removeOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_ill_all.remove_main_fact
     *
     * @return the value of public.etp_ill_all.remove_main_fact
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRemoveMainFact() {
        return removeMainFact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_ill_all.remove_main_fact
     *
     * @param removeMainFact the value for public.etp_ill_all.remove_main_fact
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRemoveMainFact(String removeMainFact) {
        this.removeMainFact = removeMainFact == null ? null : removeMainFact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_ill_all.remove_date
     *
     * @return the value of public.etp_ill_all.remove_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getRemoveDate() {
        return removeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_ill_all.remove_date
     *
     * @param removeDate the value for public.etp_ill_all.remove_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRemoveDate(Date removeDate) {
        this.removeDate = removeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_ill_all.crawl_time
     *
     * @return the value of public.etp_ill_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_ill_all.crawl_time
     *
     * @param crawlTime the value for public.etp_ill_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }
}
