package com.masspick.peak.model.etp;

import java.math.BigDecimal;
import java.util.Date;

/**
 * EtpShareholder
 */
public class EtpShareholder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String etpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.detail_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.shareholder
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String shareholder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.holder_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String holderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.holder_type_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String holderTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.card_no
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.card_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.card_type_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String cardTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.address
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.confusing_amount
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Double confusingAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.confusing_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date confusingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.confusing_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String confusingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.payment
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.payment_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date paymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.payment_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.country_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String countryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.open_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String outId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shareholder_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date crawlTime;

    /**
     * rate
     */
    private String rate;

    /**
     * Gets rate
     *
     * @return value of rate
     */
    public String getRate() {
        return rate;
    }

    /**
     * @param rate
     */
    public void setRate(String rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.id
     *
     * @return the value of public.etp_shareholder_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.id
     *
     * @param id the value for public.etp_shareholder_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.etp_id
     *
     * @return the value of public.etp_shareholder_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEtpId() {
        return etpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.etp_id
     *
     * @param etpId the value for public.etp_shareholder_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEtpId(String etpId) {
        this.etpId = etpId == null ? null : etpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.detail_id
     *
     * @return the value of public.etp_shareholder_all.detail_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.detail_id
     *
     * @param detailId the value for public.etp_shareholder_all.detail_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setDetailId(String detailId) {
        this.detailId = detailId == null ? null : detailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.shareholder
     *
     * @return the value of public.etp_shareholder_all.shareholder
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getShareholder() {
        return shareholder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.shareholder
     *
     * @param shareholder the value for public.etp_shareholder_all.shareholder
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setShareholder(String shareholder) {
        this.shareholder = shareholder == null ? null : shareholder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.holder_type
     *
     * @return the value of public.etp_shareholder_all.holder_type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getHolderType() {
        return holderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.holder_type
     *
     * @param holderType the value for public.etp_shareholder_all.holder_type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setHolderType(String holderType) {
        this.holderType = holderType == null ? null : holderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.holder_type_name
     *
     * @return the value of public.etp_shareholder_all.holder_type_name
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getHolderTypeName() {
        return holderTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.holder_type_name
     *
     * @param holderTypeName the value for public.etp_shareholder_all.holder_type_name
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setHolderTypeName(String holderTypeName) {
        this.holderTypeName = holderTypeName == null ? null : holderTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.card_no
     *
     * @return the value of public.etp_shareholder_all.card_no
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.card_no
     *
     * @param cardNo the value for public.etp_shareholder_all.card_no
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.card_type
     *
     * @return the value of public.etp_shareholder_all.card_type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.card_type
     *
     * @param cardType the value for public.etp_shareholder_all.card_type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.card_type_name
     *
     * @return the value of public.etp_shareholder_all.card_type_name
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCardTypeName() {
        return cardTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.card_type_name
     *
     * @param cardTypeName the value for public.etp_shareholder_all.card_type_name
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCardTypeName(String cardTypeName) {
        this.cardTypeName = cardTypeName == null ? null : cardTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.address
     *
     * @return the value of public.etp_shareholder_all.address
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.address
     *
     * @param address the value for public.etp_shareholder_all.address
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.confusing_amount
     *
     * @return the value of public.etp_shareholder_all.confusing_amount
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Double getConfusingAmount() {
        return confusingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.confusing_amount
     *
     * @param confusingAmount the value for public.etp_shareholder_all.confusing_amount
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setConfusingAmount(Double confusingAmount) {
        this.confusingAmount = confusingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.confusing_date
     *
     * @return the value of public.etp_shareholder_all.confusing_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getConfusingDate() {
        return confusingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.confusing_date
     *
     * @param confusingDate the value for public.etp_shareholder_all.confusing_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setConfusingDate(Date confusingDate) {
        this.confusingDate = confusingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.confusing_type
     *
     * @return the value of public.etp_shareholder_all.confusing_type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getConfusingType() {
        return confusingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.confusing_type
     *
     * @param confusingType the value for public.etp_shareholder_all.confusing_type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setConfusingType(String confusingType) {
        this.confusingType = confusingType == null ? null : confusingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.payment
     *
     * @return the value of public.etp_shareholder_all.payment
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.payment
     *
     * @param payment the value for public.etp_shareholder_all.payment
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.payment_date
     *
     * @return the value of public.etp_shareholder_all.payment_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.payment_date
     *
     * @param paymentDate the value for public.etp_shareholder_all.payment_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.payment_type
     *
     * @return the value of public.etp_shareholder_all.payment_type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.payment_type
     *
     * @param paymentType the value for public.etp_shareholder_all.payment_type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.country_name
     *
     * @return the value of public.etp_shareholder_all.country_name
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.country_name
     *
     * @param countryName the value for public.etp_shareholder_all.country_name
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.open_date
     *
     * @return the value of public.etp_shareholder_all.open_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.open_date
     *
     * @param openDate the value for public.etp_shareholder_all.open_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.out_id
     *
     * @return the value of public.etp_shareholder_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.out_id
     *
     * @param outId the value for public.etp_shareholder_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shareholder_all.crawl_time
     *
     * @return the value of public.etp_shareholder_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shareholder_all.crawl_time
     *
     * @param crawlTime the value for public.etp_shareholder_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }
}
