package com.masspick.peak.model.etp;

import java.math.BigDecimal;
import java.util.Date;

/**
 * EtpSharesFrost
 */
public class EtpSharesFrost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String etpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.executor
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String executor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.execute_no
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String executeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.stock_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private BigDecimal stockNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.stock_num_unit
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String stockNumUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.stock_num_cap_cur
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String stockNumCapCur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.decide_org
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String decideOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.frozen_state
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String frozenState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.ext_start_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date extStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.ext_end_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date extEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.ext_card_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String extCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.ext_card_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String extCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.ext_matter
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String extMatter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.ext_term
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String extTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.public_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date publicDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.ext_judge_no
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String extJudgeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String outId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_shares_frost_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date crawlTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.id
     *
     * @return the value of public.etp_shares_frost_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.id
     *
     * @param id the value for public.etp_shares_frost_all.id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.etp_id
     *
     * @return the value of public.etp_shares_frost_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEtpId() {
        return etpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.etp_id
     *
     * @param etpId the value for public.etp_shares_frost_all.etp_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEtpId(String etpId) {
        this.etpId = etpId == null ? null : etpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.executor
     *
     * @return the value of public.etp_shares_frost_all.executor
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getExecutor() {
        return executor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.executor
     *
     * @param executor the value for public.etp_shares_frost_all.executor
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setExecutor(String executor) {
        this.executor = executor == null ? null : executor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.execute_no
     *
     * @return the value of public.etp_shares_frost_all.execute_no
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getExecuteNo() {
        return executeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.execute_no
     *
     * @param executeNo the value for public.etp_shares_frost_all.execute_no
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setExecuteNo(String executeNo) {
        this.executeNo = executeNo == null ? null : executeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.stock_num
     *
     * @return the value of public.etp_shares_frost_all.stock_num
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public BigDecimal getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.stock_num
     *
     * @param stockNum the value for public.etp_shares_frost_all.stock_num
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setStockNum(BigDecimal stockNum) {
        this.stockNum = stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.stock_num_unit
     *
     * @return the value of public.etp_shares_frost_all.stock_num_unit
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getStockNumUnit() {
        return stockNumUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.stock_num_unit
     *
     * @param stockNumUnit the value for public.etp_shares_frost_all.stock_num_unit
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setStockNumUnit(String stockNumUnit) {
        this.stockNumUnit = stockNumUnit == null ? null : stockNumUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.stock_num_cap_cur
     *
     * @return the value of public.etp_shares_frost_all.stock_num_cap_cur
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getStockNumCapCur() {
        return stockNumCapCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.stock_num_cap_cur
     *
     * @param stockNumCapCur the value for public.etp_shares_frost_all.stock_num_cap_cur
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setStockNumCapCur(String stockNumCapCur) {
        this.stockNumCapCur = stockNumCapCur == null ? null : stockNumCapCur.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.decide_org
     *
     * @return the value of public.etp_shares_frost_all.decide_org
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getDecideOrg() {
        return decideOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.decide_org
     *
     * @param decideOrg the value for public.etp_shares_frost_all.decide_org
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setDecideOrg(String decideOrg) {
        this.decideOrg = decideOrg == null ? null : decideOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.frozen_state
     *
     * @return the value of public.etp_shares_frost_all.frozen_state
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getFrozenState() {
        return frozenState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.frozen_state
     *
     * @param frozenState the value for public.etp_shares_frost_all.frozen_state
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setFrozenState(String frozenState) {
        this.frozenState = frozenState == null ? null : frozenState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.ext_start_date
     *
     * @return the value of public.etp_shares_frost_all.ext_start_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getExtStartDate() {
        return extStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.ext_start_date
     *
     * @param extStartDate the value for public.etp_shares_frost_all.ext_start_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setExtStartDate(Date extStartDate) {
        this.extStartDate = extStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.ext_end_date
     *
     * @return the value of public.etp_shares_frost_all.ext_end_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getExtEndDate() {
        return extEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.ext_end_date
     *
     * @param extEndDate the value for public.etp_shares_frost_all.ext_end_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setExtEndDate(Date extEndDate) {
        this.extEndDate = extEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.ext_card_id
     *
     * @return the value of public.etp_shares_frost_all.ext_card_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getExtCardId() {
        return extCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.ext_card_id
     *
     * @param extCardId the value for public.etp_shares_frost_all.ext_card_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setExtCardId(String extCardId) {
        this.extCardId = extCardId == null ? null : extCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.ext_card_type
     *
     * @return the value of public.etp_shares_frost_all.ext_card_type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getExtCardType() {
        return extCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.ext_card_type
     *
     * @param extCardType the value for public.etp_shares_frost_all.ext_card_type
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setExtCardType(String extCardType) {
        this.extCardType = extCardType == null ? null : extCardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.ext_matter
     *
     * @return the value of public.etp_shares_frost_all.ext_matter
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getExtMatter() {
        return extMatter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.ext_matter
     *
     * @param extMatter the value for public.etp_shares_frost_all.ext_matter
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setExtMatter(String extMatter) {
        this.extMatter = extMatter == null ? null : extMatter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.ext_term
     *
     * @return the value of public.etp_shares_frost_all.ext_term
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getExtTerm() {
        return extTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.ext_term
     *
     * @param extTerm the value for public.etp_shares_frost_all.ext_term
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setExtTerm(String extTerm) {
        this.extTerm = extTerm == null ? null : extTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.public_date
     *
     * @return the value of public.etp_shares_frost_all.public_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getPublicDate() {
        return publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.public_date
     *
     * @param publicDate the value for public.etp_shares_frost_all.public_date
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPublicDate(Date publicDate) {
        this.publicDate = publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.ext_judge_no
     *
     * @return the value of public.etp_shares_frost_all.ext_judge_no
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getExtJudgeNo() {
        return extJudgeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.ext_judge_no
     *
     * @param extJudgeNo the value for public.etp_shares_frost_all.ext_judge_no
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setExtJudgeNo(String extJudgeNo) {
        this.extJudgeNo = extJudgeNo == null ? null : extJudgeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.out_id
     *
     * @return the value of public.etp_shares_frost_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.out_id
     *
     * @param outId the value for public.etp_shares_frost_all.out_id
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_shares_frost_all.crawl_time
     *
     * @return the value of public.etp_shares_frost_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_shares_frost_all.crawl_time
     *
     * @param crawlTime the value for public.etp_shares_frost_all.crawl_time
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }
}
