package com.masspick.peak.model.dto.etp;

import java.util.Date;

/**
 * Created by admin on 2018/7/6 0006.
 */
public class EtpPunishDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String etpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.court_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String courtNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.ilegal_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String ilegalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.case_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.punish_type_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String punishTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.content
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.decision_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String decisionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.punish_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date punishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.public_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date publicDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.remark
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.is_public
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String isPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.last_modified_person
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String lastModifiedPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.last_modified_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date lastModifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date crawlTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_punish_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String outId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.id
     *
     * @return the value of public.etp_punish_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.id
     *
     * @param id the value for public.etp_punish_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.etp_id
     *
     * @return the value of public.etp_punish_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEtpId() {
        return etpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.etp_id
     *
     * @param etpId the value for public.etp_punish_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEtpId(String etpId) {
        this.etpId = etpId == null ? null : etpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.court_num
     *
     * @return the value of public.etp_punish_all.court_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCourtNum() {
        return courtNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.court_num
     *
     * @param courtNum the value for public.etp_punish_all.court_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCourtNum(String courtNum) {
        this.courtNum = courtNum == null ? null : courtNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.ilegal_type
     *
     * @return the value of public.etp_punish_all.ilegal_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getIlegalType() {
        return ilegalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.ilegal_type
     *
     * @param ilegalType the value for public.etp_punish_all.ilegal_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setIlegalType(String ilegalType) {
        this.ilegalType = ilegalType == null ? null : ilegalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.case_id
     *
     * @return the value of public.etp_punish_all.case_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.case_id
     *
     * @param caseId the value for public.etp_punish_all.case_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.punish_type_name
     *
     * @return the value of public.etp_punish_all.punish_type_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPunishTypeName() {
        return punishTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.punish_type_name
     *
     * @param punishTypeName the value for public.etp_punish_all.punish_type_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPunishTypeName(String punishTypeName) {
        this.punishTypeName = punishTypeName == null ? null : punishTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.content
     *
     * @return the value of public.etp_punish_all.content
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.content
     *
     * @param content the value for public.etp_punish_all.content
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.decision_name
     *
     * @return the value of public.etp_punish_all.decision_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getDecisionName() {
        return decisionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.decision_name
     *
     * @param decisionName the value for public.etp_punish_all.decision_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setDecisionName(String decisionName) {
        this.decisionName = decisionName == null ? null : decisionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.punish_date
     *
     * @return the value of public.etp_punish_all.punish_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getPunishDate() {
        return punishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.punish_date
     *
     * @param punishDate the value for public.etp_punish_all.punish_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPunishDate(Date punishDate) {
        this.punishDate = punishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.public_date
     *
     * @return the value of public.etp_punish_all.public_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getPublicDate() {
        return publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.public_date
     *
     * @param publicDate the value for public.etp_punish_all.public_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPublicDate(Date publicDate) {
        this.publicDate = publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.remark
     *
     * @return the value of public.etp_punish_all.remark
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.remark
     *
     * @param remark the value for public.etp_punish_all.remark
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.is_public
     *
     * @return the value of public.etp_punish_all.is_public
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.is_public
     *
     * @param isPublic the value for public.etp_punish_all.is_public
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setIsPublic(String isPublic) {
        this.isPublic = isPublic == null ? null : isPublic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.last_modified_person
     *
     * @return the value of public.etp_punish_all.last_modified_person
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getLastModifiedPerson() {
        return lastModifiedPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.last_modified_person
     *
     * @param lastModifiedPerson the value for public.etp_punish_all.last_modified_person
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setLastModifiedPerson(String lastModifiedPerson) {
        this.lastModifiedPerson = lastModifiedPerson == null ? null : lastModifiedPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.last_modified_time
     *
     * @return the value of public.etp_punish_all.last_modified_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.last_modified_time
     *
     * @param lastModifiedTime the value for public.etp_punish_all.last_modified_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.crawl_time
     *
     * @return the value of public.etp_punish_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.crawl_time
     *
     * @param crawlTime the value for public.etp_punish_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_punish_all.out_id
     *
     * @return the value of public.etp_punish_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_punish_all.out_id
     *
     * @param outId the value for public.etp_punish_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }
}
