package com.masspick.peak.model.dto.etp;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Created by admin on 2018/7/6 0006.
 */
public class EtpStockDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String etpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.reg_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String regNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.pledgor
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String pledgor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.pledgor_card_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String pledgorCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.pledgor_card_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String pledgorCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.pledgor_card_type_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String pledgorCardTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.stock_amount
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private BigDecimal stockAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.pledgee
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String pledgee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.pledgee_card_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String pledgeeCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.pledgee_card_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String pledgeeCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.pledgee_card_type_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String pledgeeCardTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.reg_cap_cur
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String regCapCur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.reg_cap_cur_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String regCapCurName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.reg_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.state
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String outId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.can_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date canDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.pled_am_unit
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String pledAmUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.equ_ple_can_rea
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String equPleCanRea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.public_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date publicDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.cancel_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date cancelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.cancel_rea
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String cancelRea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.alt_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date altDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.v_stak_qualit_info_alt
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String vStakQualitInfoAlt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.type_cn
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private String typeCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.etp_stock_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    private Date crawlTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.id
     *
     * @return the value of public.etp_stock_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.id
     *
     * @param id the value for public.etp_stock_all.id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.etp_id
     *
     * @return the value of public.etp_stock_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEtpId() {
        return etpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.etp_id
     *
     * @param etpId the value for public.etp_stock_all.etp_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEtpId(String etpId) {
        this.etpId = etpId == null ? null : etpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.reg_num
     *
     * @return the value of public.etp_stock_all.reg_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRegNum() {
        return regNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.reg_num
     *
     * @param regNum the value for public.etp_stock_all.reg_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegNum(String regNum) {
        this.regNum = regNum == null ? null : regNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.pledgor
     *
     * @return the value of public.etp_stock_all.pledgor
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPledgor() {
        return pledgor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.pledgor
     *
     * @param pledgor the value for public.etp_stock_all.pledgor
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPledgor(String pledgor) {
        this.pledgor = pledgor == null ? null : pledgor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.pledgor_card_num
     *
     * @return the value of public.etp_stock_all.pledgor_card_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPledgorCardNum() {
        return pledgorCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.pledgor_card_num
     *
     * @param pledgorCardNum the value for public.etp_stock_all.pledgor_card_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPledgorCardNum(String pledgorCardNum) {
        this.pledgorCardNum = pledgorCardNum == null ? null : pledgorCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.pledgor_card_type
     *
     * @return the value of public.etp_stock_all.pledgor_card_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPledgorCardType() {
        return pledgorCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.pledgor_card_type
     *
     * @param pledgorCardType the value for public.etp_stock_all.pledgor_card_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPledgorCardType(String pledgorCardType) {
        this.pledgorCardType = pledgorCardType == null ? null : pledgorCardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.pledgor_card_type_name
     *
     * @return the value of public.etp_stock_all.pledgor_card_type_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPledgorCardTypeName() {
        return pledgorCardTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.pledgor_card_type_name
     *
     * @param pledgorCardTypeName the value for public.etp_stock_all.pledgor_card_type_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPledgorCardTypeName(String pledgorCardTypeName) {
        this.pledgorCardTypeName = pledgorCardTypeName == null ? null : pledgorCardTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.stock_amount
     *
     * @return the value of public.etp_stock_all.stock_amount
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public BigDecimal getStockAmount() {
        return stockAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.stock_amount
     *
     * @param stockAmount the value for public.etp_stock_all.stock_amount
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setStockAmount(BigDecimal stockAmount) {
        this.stockAmount = stockAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.pledgee
     *
     * @return the value of public.etp_stock_all.pledgee
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPledgee() {
        return pledgee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.pledgee
     *
     * @param pledgee the value for public.etp_stock_all.pledgee
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPledgee(String pledgee) {
        this.pledgee = pledgee == null ? null : pledgee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.pledgee_card_num
     *
     * @return the value of public.etp_stock_all.pledgee_card_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPledgeeCardNum() {
        return pledgeeCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.pledgee_card_num
     *
     * @param pledgeeCardNum the value for public.etp_stock_all.pledgee_card_num
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPledgeeCardNum(String pledgeeCardNum) {
        this.pledgeeCardNum = pledgeeCardNum == null ? null : pledgeeCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.pledgee_card_type
     *
     * @return the value of public.etp_stock_all.pledgee_card_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPledgeeCardType() {
        return pledgeeCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.pledgee_card_type
     *
     * @param pledgeeCardType the value for public.etp_stock_all.pledgee_card_type
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPledgeeCardType(String pledgeeCardType) {
        this.pledgeeCardType = pledgeeCardType == null ? null : pledgeeCardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.pledgee_card_type_name
     *
     * @return the value of public.etp_stock_all.pledgee_card_type_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPledgeeCardTypeName() {
        return pledgeeCardTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.pledgee_card_type_name
     *
     * @param pledgeeCardTypeName the value for public.etp_stock_all.pledgee_card_type_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPledgeeCardTypeName(String pledgeeCardTypeName) {
        this.pledgeeCardTypeName = pledgeeCardTypeName == null ? null : pledgeeCardTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.reg_cap_cur
     *
     * @return the value of public.etp_stock_all.reg_cap_cur
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRegCapCur() {
        return regCapCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.reg_cap_cur
     *
     * @param regCapCur the value for public.etp_stock_all.reg_cap_cur
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegCapCur(String regCapCur) {
        this.regCapCur = regCapCur == null ? null : regCapCur.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.reg_cap_cur_name
     *
     * @return the value of public.etp_stock_all.reg_cap_cur_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getRegCapCurName() {
        return regCapCurName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.reg_cap_cur_name
     *
     * @param regCapCurName the value for public.etp_stock_all.reg_cap_cur_name
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegCapCurName(String regCapCurName) {
        this.regCapCurName = regCapCurName == null ? null : regCapCurName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.reg_date
     *
     * @return the value of public.etp_stock_all.reg_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.reg_date
     *
     * @param regDate the value for public.etp_stock_all.reg_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.state
     *
     * @return the value of public.etp_stock_all.state
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.state
     *
     * @param state the value for public.etp_stock_all.state
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.out_id
     *
     * @return the value of public.etp_stock_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.out_id
     *
     * @param outId the value for public.etp_stock_all.out_id
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setOutId(String outId) {
        this.outId = outId == null ? null : outId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.can_date
     *
     * @return the value of public.etp_stock_all.can_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCanDate() {
        return canDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.can_date
     *
     * @param canDate the value for public.etp_stock_all.can_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCanDate(Date canDate) {
        this.canDate = canDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.pled_am_unit
     *
     * @return the value of public.etp_stock_all.pled_am_unit
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getPledAmUnit() {
        return pledAmUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.pled_am_unit
     *
     * @param pledAmUnit the value for public.etp_stock_all.pled_am_unit
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPledAmUnit(String pledAmUnit) {
        this.pledAmUnit = pledAmUnit == null ? null : pledAmUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.equ_ple_can_rea
     *
     * @return the value of public.etp_stock_all.equ_ple_can_rea
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getEquPleCanRea() {
        return equPleCanRea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.equ_ple_can_rea
     *
     * @param equPleCanRea the value for public.etp_stock_all.equ_ple_can_rea
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setEquPleCanRea(String equPleCanRea) {
        this.equPleCanRea = equPleCanRea == null ? null : equPleCanRea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.public_date
     *
     * @return the value of public.etp_stock_all.public_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getPublicDate() {
        return publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.public_date
     *
     * @param publicDate the value for public.etp_stock_all.public_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setPublicDate(Date publicDate) {
        this.publicDate = publicDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.cancel_date
     *
     * @return the value of public.etp_stock_all.cancel_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCancelDate() {
        return cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.cancel_date
     *
     * @param cancelDate the value for public.etp_stock_all.cancel_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCancelDate(Date cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.cancel_rea
     *
     * @return the value of public.etp_stock_all.cancel_rea
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getCancelRea() {
        return cancelRea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.cancel_rea
     *
     * @param cancelRea the value for public.etp_stock_all.cancel_rea
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCancelRea(String cancelRea) {
        this.cancelRea = cancelRea == null ? null : cancelRea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.alt_date
     *
     * @return the value of public.etp_stock_all.alt_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getAltDate() {
        return altDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.alt_date
     *
     * @param altDate the value for public.etp_stock_all.alt_date
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setAltDate(Date altDate) {
        this.altDate = altDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.v_stak_qualit_info_alt
     *
     * @return the value of public.etp_stock_all.v_stak_qualit_info_alt
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getvStakQualitInfoAlt() {
        return vStakQualitInfoAlt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.v_stak_qualit_info_alt
     *
     * @param vStakQualitInfoAlt the value for public.etp_stock_all.v_stak_qualit_info_alt
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setvStakQualitInfoAlt(String vStakQualitInfoAlt) {
        this.vStakQualitInfoAlt = vStakQualitInfoAlt == null ? null : vStakQualitInfoAlt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.type_cn
     *
     * @return the value of public.etp_stock_all.type_cn
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public String getTypeCn() {
        return typeCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.type_cn
     *
     * @param typeCn the value for public.etp_stock_all.type_cn
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setTypeCn(String typeCn) {
        this.typeCn = typeCn == null ? null : typeCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.etp_stock_all.crawl_time
     *
     * @return the value of public.etp_stock_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.etp_stock_all.crawl_time
     *
     * @param crawlTime the value for public.etp_stock_all.crawl_time
     *
     * @mbggenerated Mon Jun 11 16:05:10 CST 2018
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }
}
