version: '3'
services:
  decision-client:
    image: ccr.ccs.tencentyun.com/bjd_bigdata/peak-decision:${VERSION}
    environment:
      - EUREKA_MEMBERS=http://eureka1:8761/eureka/,http://eureka2:8761/eureka/,http://eureka3:8761/eureka/
      - SPRING_PREFER_NETWORK=10.0.0
      - ENV=prod
      - JDBC_URL=192.168.0.55
      - JDBC_PORT=3306
      - JDBC_USERNAME=root
      - JDBC_PASSWORD=${JDBC_PASSWORD}
    networks:
      springcloud-overlay:
        aliases:
          - peakDecisionClient
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay