pipeline {
    agent { 
        node { label 'maven' } 
    }
    parameters {
        string(name: 'SPRING_PREFER_NETWORK', defaultValue: '10.0.100',
            description: 'Which container network spring cloud use?')
        string(name: 'JDBC_URL', defaultValue: '192.168.0.55',
            description: 'jdbc host?')
        string(name: 'JDBC_PORT', defaultValue: '3306',
            description: 'jdbc port?')
        string(name: 'JDBC_USERNAME', defaultValue: 'root',
            description: 'jdbc username?')
        string(name: 'JDBC_PASSWORD', defaultValue: '',
            description: 'jdbc password?')
        string(name: 'SPRING_OVERLAY_SUBNET', defaultValue: '10.0.100.0/24',
            description: 'Which container network to create?')
        booleanParam(name: 'DEPLOY', defaultValue: false,
            description: 'Should update deploy or not?')
    }
    stages {
        stage('Package') {
            steps {
               dir('peak-decision'){
                  sh 'make docker-build'
               }
            }
            post {
                success {
                    archiveArtifacts artifacts: 'peak-decision/peak-decision-client/target/*.jar', fingerprint: true
                 }
            }
        }
        stage('Upload') {
            steps {
                dir('peak-decision'){
                    sh 'docker login ccr.ccs.tencentyun.com -u 100003569030 -p bigdata2018'
                    sh 'make docker-push'
                }
            }
        }
        stage('PreDeploy') {
            when {
                expression {
                    return params.CREATE_NETWORK
                }
            }
            steps {
                sh "make network SPRING_OVERLAY_SUBNET=${params.SPRING_OVERLAY_SUBNET}"
            }
        }
        stage('Deploy') {
            when {
                expression {
                    return params.DEPLOY
                }
            }
            steps {
                dir('peak-decision'){
                    sh 'make deploy'
                }
            }
        }
        
    }
}