server:
  port: 8080
logging:
  level:
    root: INFO
    com.masspick.peak.guest.mapper: debugg
  file: logs/${spring.application.name}.log



spring:
  application:
    name: peak-guest-client
  redis:
      database: 0
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: 6379
      timeout: 60000
      jedis:
        pool:
          max-active: 8 #最大连接数
          max-idle: 8 #最大空闲连接数
          max-wait: -1 #最大等待时间
          min-idle: 0
  datasource:
    url: jdbc:mysql://${JDBC_URL}:${JDBC_PORT}/peak_guest?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_MEMBERS}
  instance:
     instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

cos:
  url: https://masspick-1255853614.cos-website.ap-shanghai.myqcloud.com
  dir: masspick/produc/peak-guest/
  accessKey: AKIDPfAYmp5OuNgolWvVq35wd9TdcQ2THurd
  secretKey: kM1Vo6KSVSJ3iGk9RcfXFoDYiiXB7uVu
  region: ap-shanghai
  bucket:
    name: masspick-1255853614

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

upload:
  tempFilePath: /var/guest/

