server:
  port: 7900

logging:
  level:
    root: INFO
  file: logs/${spring.application.name}.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: peak-resource-provider
  datasource:
    url: jdbc:mysql://192.168.111.210:3306/resource?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    initial-size: 1
    min-idle: 3
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false




